/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_gestion_des_ouvriers (void);
GtkWidget* create_ajouter (void);
GtkWidget* create_modifier (void);
GtkWidget* create_formulaire (void);
GtkWidget* create_chercher (void);
GtkWidget* create_afficher (void);
GtkWidget* create_supprimer (void);
GtkWidget* create_affichage (void);
GtkWidget* create_absenteisme (void);
GtkWidget* create_surface_absenteisme (void);
