/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_gestion_des_ouvriers (void)
{
  GtkWidget *gestion_des_ouvriers;
  GtkWidget *fixed1;
  GtkWidget *modifier;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label2;
  GtkWidget *supprimer;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label4;
  GtkWidget *verification;
  GtkWidget *alignment22;
  GtkWidget *hbox22;
  GtkWidget *image22;
  GtkWidget *label57;
  GtkWidget *afficher;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label3;
  GtkWidget *chercher;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label5;
  GtkWidget *ajouter;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label1;
  GtkWidget *presence;
  GtkWidget *alignment23;
  GtkWidget *hbox23;
  GtkWidget *image23;
  GtkWidget *label58;

  gestion_des_ouvriers = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (gestion_des_ouvriers), _("gestion des ouvriers"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (gestion_des_ouvriers), fixed1);

  modifier = gtk_button_new ();
  gtk_widget_show (modifier);
  gtk_fixed_put (GTK_FIXED (fixed1), modifier, 24, 16);
  gtk_widget_set_size_request (modifier, 96, 29);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (modifier), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox2), label2, FALSE, FALSE, 0);

  supprimer = gtk_button_new ();
  gtk_widget_show (supprimer);
  gtk_fixed_put (GTK_FIXED (fixed1), supprimer, 24, 136);
  gtk_widget_set_size_request (supprimer, 104, 29);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (supprimer), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox4), label4, FALSE, FALSE, 0);

  verification = gtk_button_new ();
  gtk_widget_show (verification);
  gtk_fixed_put (GTK_FIXED (fixed1), verification, 216, 136);
  gtk_widget_set_size_request (verification, 112, 32);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (verification), alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox22);

  image22 = gtk_image_new_from_stock ("gtk-spell-check", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox22), image22, FALSE, FALSE, 0);

  label57 = gtk_label_new_with_mnemonic (_("verification"));
  gtk_widget_show (label57);
  gtk_box_pack_start (GTK_BOX (hbox22), label57, FALSE, FALSE, 0);

  afficher = gtk_button_new ();
  gtk_widget_show (afficher);
  gtk_fixed_put (GTK_FIXED (fixed1), afficher, 24, 80);
  gtk_widget_set_size_request (afficher, 96, 29);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (afficher), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-print-preview", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox3), label3, FALSE, FALSE, 0);

  chercher = gtk_button_new ();
  gtk_widget_show (chercher);
  gtk_fixed_put (GTK_FIXED (fixed1), chercher, 216, 80);
  gtk_widget_set_size_request (chercher, 112, 29);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (chercher), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox5), label5, FALSE, FALSE, 0);

  ajouter = gtk_button_new ();
  gtk_widget_show (ajouter);
  gtk_fixed_put (GTK_FIXED (fixed1), ajouter, 216, 16);
  gtk_widget_set_size_request (ajouter, 112, 29);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (ajouter), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);

  presence = gtk_button_new ();
  gtk_widget_show (presence);
  gtk_fixed_put (GTK_FIXED (fixed1), presence, 136, 192);
  gtk_widget_set_size_request (presence, 96, 29);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (presence), alignment23);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox23);

  image23 = gtk_image_new_from_stock ("gtk-cdrom", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox23), image23, FALSE, FALSE, 0);

  label58 = gtk_label_new_with_mnemonic (_("presence"));
  gtk_widget_show (label58);
  gtk_box_pack_start (GTK_BOX (hbox23), label58, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) modifier, "clicked",
                    G_CALLBACK (on_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimer, "clicked",
                    G_CALLBACK (on_supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) verification, "clicked",
                    G_CALLBACK (on_verification_clicked),
                    NULL);
  g_signal_connect ((gpointer) afficher, "clicked",
                    G_CALLBACK (on_afficher_clicked),
                    NULL);
  g_signal_connect ((gpointer) chercher, "clicked",
                    G_CALLBACK (on_chercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouter, "clicked",
                    G_CALLBACK (on_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) presence, "clicked",
                    G_CALLBACK (on_presence_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gestion_des_ouvriers, gestion_des_ouvriers, "gestion_des_ouvriers");
  GLADE_HOOKUP_OBJECT (gestion_des_ouvriers, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (gestion_des_ouvriers, modifier, "modifier");
  GLADE_HOOKUP_OBJECT (gestion_des_ouvriers, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (gestion_des_ouvriers, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (gestion_des_ouvriers, image2, "image2");
  GLADE_HOOKUP_OBJECT (gestion_des_ouvriers, label2, "label2");
  GLADE_HOOKUP_OBJECT (gestion_des_ouvriers, supprimer, "supprimer");
  GLADE_HOOKUP_OBJECT (gestion_des_ouvriers, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (gestion_des_ouvriers, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (gestion_des_ouvriers, image4, "image4");
  GLADE_HOOKUP_OBJECT (gestion_des_ouvriers, label4, "label4");
  GLADE_HOOKUP_OBJECT (gestion_des_ouvriers, verification, "verification");
  GLADE_HOOKUP_OBJECT (gestion_des_ouvriers, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (gestion_des_ouvriers, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (gestion_des_ouvriers, image22, "image22");
  GLADE_HOOKUP_OBJECT (gestion_des_ouvriers, label57, "label57");
  GLADE_HOOKUP_OBJECT (gestion_des_ouvriers, afficher, "afficher");
  GLADE_HOOKUP_OBJECT (gestion_des_ouvriers, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (gestion_des_ouvriers, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (gestion_des_ouvriers, image3, "image3");
  GLADE_HOOKUP_OBJECT (gestion_des_ouvriers, label3, "label3");
  GLADE_HOOKUP_OBJECT (gestion_des_ouvriers, chercher, "chercher");
  GLADE_HOOKUP_OBJECT (gestion_des_ouvriers, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (gestion_des_ouvriers, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (gestion_des_ouvriers, image5, "image5");
  GLADE_HOOKUP_OBJECT (gestion_des_ouvriers, label5, "label5");
  GLADE_HOOKUP_OBJECT (gestion_des_ouvriers, ajouter, "ajouter");
  GLADE_HOOKUP_OBJECT (gestion_des_ouvriers, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (gestion_des_ouvriers, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (gestion_des_ouvriers, image1, "image1");
  GLADE_HOOKUP_OBJECT (gestion_des_ouvriers, label1, "label1");
  GLADE_HOOKUP_OBJECT (gestion_des_ouvriers, presence, "presence");
  GLADE_HOOKUP_OBJECT (gestion_des_ouvriers, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (gestion_des_ouvriers, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (gestion_des_ouvriers, image23, "image23");
  GLADE_HOOKUP_OBJECT (gestion_des_ouvriers, label58, "label58");

  return gestion_des_ouvriers;
}

GtkWidget*
create_ajouter (void)
{
  GtkWidget *ajouter;
  GtkWidget *fixed2;
  GtkWidget *entry1_nom;
  GtkWidget *entry2_prenom;
  GtkWidget *entry3_cin;
  GtkObject *spinbutton1_jour_adj;
  GtkWidget *spinbutton1_jour;
  GtkObject *spinbutton2_mois_adj;
  GtkWidget *spinbutton2_mois;
  GtkObject *spinbutton3_annee_adj;
  GtkWidget *spinbutton3_annee;
  GtkObject *spinbutton4_jour_adj;
  GtkWidget *spinbutton4_jour;
  GtkObject *spinbutton5_mois_adj;
  GtkWidget *spinbutton5_mois;
  GtkObject *spinbutton6_annee_adj;
  GtkWidget *spinbutton6_annee;
  GtkWidget *entry4_adresse;
  GtkWidget *entry5_num;
  GtkWidget *annuler;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label15;
  GtkWidget *prenom;
  GtkWidget *nom;
  GtkWidget *cin;
  GtkWidget *date_de_recrutement;
  GtkWidget *date_de_naissance;
  GtkWidget *sexe;
  GtkWidget *adresse;
  GtkWidget *num_de_telephone;
  GtkWidget *combobox1;
  GtkWidget *valider;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label14;

  ajouter = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajouter), _("ajouter"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (ajouter), fixed2);

  entry1_nom = gtk_entry_new ();
  gtk_widget_show (entry1_nom);
  gtk_fixed_put (GTK_FIXED (fixed2), entry1_nom, 224, 8);
  gtk_widget_set_size_request (entry1_nom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1_nom), 8226);

  entry2_prenom = gtk_entry_new ();
  gtk_widget_show (entry2_prenom);
  gtk_fixed_put (GTK_FIXED (fixed2), entry2_prenom, 224, 40);
  gtk_widget_set_size_request (entry2_prenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2_prenom), 8226);

  entry3_cin = gtk_entry_new ();
  gtk_widget_show (entry3_cin);
  gtk_fixed_put (GTK_FIXED (fixed2), entry3_cin, 224, 72);
  gtk_widget_set_size_request (entry3_cin, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3_cin), 8226);

  spinbutton1_jour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton1_jour = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_jour_adj), 1, 0);
  gtk_widget_show (spinbutton1_jour);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton1_jour, 216, 104);
  gtk_widget_set_size_request (spinbutton1_jour, 48, 24);

  spinbutton2_mois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton2_mois = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_mois_adj), 1, 0);
  gtk_widget_show (spinbutton2_mois);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton2_mois, 264, 104);
  gtk_widget_set_size_request (spinbutton2_mois, 48, 24);

  spinbutton3_annee_adj = gtk_adjustment_new (1, 1990, 2025, 1, 10, 10);
  spinbutton3_annee = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_annee_adj), 1, 0);
  gtk_widget_show (spinbutton3_annee);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton3_annee, 328, 104);
  gtk_widget_set_size_request (spinbutton3_annee, 60, 27);

  spinbutton4_jour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton4_jour = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_jour_adj), 1, 0);
  gtk_widget_show (spinbutton4_jour);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton4_jour, 216, 136);
  gtk_widget_set_size_request (spinbutton4_jour, 48, 24);

  spinbutton5_mois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton5_mois = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5_mois_adj), 1, 0);
  gtk_widget_show (spinbutton5_mois);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton5_mois, 264, 136);
  gtk_widget_set_size_request (spinbutton5_mois, 48, 24);

  spinbutton6_annee_adj = gtk_adjustment_new (1, 1990, 2020, 1, 10, 10);
  spinbutton6_annee = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6_annee_adj), 1, 0);
  gtk_widget_show (spinbutton6_annee);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton6_annee, 328, 136);
  gtk_widget_set_size_request (spinbutton6_annee, 60, 27);

  entry4_adresse = gtk_entry_new ();
  gtk_widget_show (entry4_adresse);
  gtk_fixed_put (GTK_FIXED (fixed2), entry4_adresse, 224, 200);
  gtk_widget_set_size_request (entry4_adresse, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4_adresse), 8226);

  entry5_num = gtk_entry_new ();
  gtk_widget_show (entry5_num);
  gtk_fixed_put (GTK_FIXED (fixed2), entry5_num, 224, 232);
  gtk_widget_set_size_request (entry5_num, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5_num), 8226);

  annuler = gtk_button_new ();
  gtk_widget_show (annuler);
  gtk_fixed_put (GTK_FIXED (fixed2), annuler, 192, 280);
  gtk_widget_set_size_request (annuler, 88, 29);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (annuler), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox7), label15, FALSE, FALSE, 0);

  prenom = gtk_label_new (_("Prenom"));
  gtk_widget_show (prenom);
  gtk_fixed_put (GTK_FIXED (fixed2), prenom, 24, 40);
  gtk_widget_set_size_request (prenom, 72, 25);

  nom = gtk_label_new (_("Nom"));
  gtk_widget_show (nom);
  gtk_fixed_put (GTK_FIXED (fixed2), nom, 40, 8);
  gtk_widget_set_size_request (nom, 41, 17);

  cin = gtk_label_new (_("Cin"));
  gtk_widget_show (cin);
  gtk_fixed_put (GTK_FIXED (fixed2), cin, 32, 80);
  gtk_widget_set_size_request (cin, 41, 17);

  date_de_recrutement = gtk_label_new (_("Date de rerutement"));
  gtk_widget_show (date_de_recrutement);
  gtk_fixed_put (GTK_FIXED (fixed2), date_de_recrutement, 32, 104);
  gtk_widget_set_size_request (date_de_recrutement, 144, 25);

  date_de_naissance = gtk_label_new (_("Date de naissance"));
  gtk_widget_show (date_de_naissance);
  gtk_fixed_put (GTK_FIXED (fixed2), date_de_naissance, 32, 136);
  gtk_widget_set_size_request (date_de_naissance, 136, 24);

  sexe = gtk_label_new (_("Sexe"));
  gtk_widget_show (sexe);
  gtk_fixed_put (GTK_FIXED (fixed2), sexe, 40, 168);
  gtk_widget_set_size_request (sexe, 49, 17);

  adresse = gtk_label_new (_("Adresse"));
  gtk_widget_show (adresse);
  gtk_fixed_put (GTK_FIXED (fixed2), adresse, 32, 200);
  gtk_widget_set_size_request (adresse, 88, 25);

  num_de_telephone = gtk_label_new (_("Num de telephone"));
  gtk_widget_show (num_de_telephone);
  gtk_fixed_put (GTK_FIXED (fixed2), num_de_telephone, 24, 232);
  gtk_widget_set_size_request (num_de_telephone, 128, 33);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed2), combobox1, 224, 168);
  gtk_widget_set_size_request (combobox1, 150, 30);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("homme"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("femme"));

  valider = gtk_button_new ();
  gtk_widget_show (valider);
  gtk_fixed_put (GTK_FIXED (fixed2), valider, 80, 280);
  gtk_widget_set_size_request (valider, 80, 29);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (valider), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox6), label14, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) annuler, "clicked",
                    G_CALLBACK (on_annuler_clicked),
                    NULL);
  g_signal_connect ((gpointer) valider, "clicked",
                    G_CALLBACK (on_valider_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajouter, ajouter, "ajouter");
  GLADE_HOOKUP_OBJECT (ajouter, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (ajouter, entry1_nom, "entry1_nom");
  GLADE_HOOKUP_OBJECT (ajouter, entry2_prenom, "entry2_prenom");
  GLADE_HOOKUP_OBJECT (ajouter, entry3_cin, "entry3_cin");
  GLADE_HOOKUP_OBJECT (ajouter, spinbutton1_jour, "spinbutton1_jour");
  GLADE_HOOKUP_OBJECT (ajouter, spinbutton2_mois, "spinbutton2_mois");
  GLADE_HOOKUP_OBJECT (ajouter, spinbutton3_annee, "spinbutton3_annee");
  GLADE_HOOKUP_OBJECT (ajouter, spinbutton4_jour, "spinbutton4_jour");
  GLADE_HOOKUP_OBJECT (ajouter, spinbutton5_mois, "spinbutton5_mois");
  GLADE_HOOKUP_OBJECT (ajouter, spinbutton6_annee, "spinbutton6_annee");
  GLADE_HOOKUP_OBJECT (ajouter, entry4_adresse, "entry4_adresse");
  GLADE_HOOKUP_OBJECT (ajouter, entry5_num, "entry5_num");
  GLADE_HOOKUP_OBJECT (ajouter, annuler, "annuler");
  GLADE_HOOKUP_OBJECT (ajouter, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (ajouter, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (ajouter, image7, "image7");
  GLADE_HOOKUP_OBJECT (ajouter, label15, "label15");
  GLADE_HOOKUP_OBJECT (ajouter, prenom, "prenom");
  GLADE_HOOKUP_OBJECT (ajouter, nom, "nom");
  GLADE_HOOKUP_OBJECT (ajouter, cin, "cin");
  GLADE_HOOKUP_OBJECT (ajouter, date_de_recrutement, "date_de_recrutement");
  GLADE_HOOKUP_OBJECT (ajouter, date_de_naissance, "date_de_naissance");
  GLADE_HOOKUP_OBJECT (ajouter, sexe, "sexe");
  GLADE_HOOKUP_OBJECT (ajouter, adresse, "adresse");
  GLADE_HOOKUP_OBJECT (ajouter, num_de_telephone, "num_de_telephone");
  GLADE_HOOKUP_OBJECT (ajouter, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (ajouter, valider, "valider");
  GLADE_HOOKUP_OBJECT (ajouter, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (ajouter, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (ajouter, image6, "image6");
  GLADE_HOOKUP_OBJECT (ajouter, label14, "label14");

  return ajouter;
}

GtkWidget*
create_modifier (void)
{
  GtkWidget *modifier;
  GtkWidget *fixed3;
  GtkWidget *label16_cin;
  GtkWidget *entry6_cin;
  GtkWidget *button9_annuler;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label18;
  GtkWidget *commentaire;
  GtkWidget *valider10;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label17;

  modifier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifier), _("modifier"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (modifier), fixed3);

  label16_cin = gtk_label_new (_("Cin"));
  gtk_widget_show (label16_cin);
  gtk_fixed_put (GTK_FIXED (fixed3), label16_cin, 56, 72);
  gtk_widget_set_size_request (label16_cin, 49, 17);

  entry6_cin = gtk_entry_new ();
  gtk_widget_show (entry6_cin);
  gtk_fixed_put (GTK_FIXED (fixed3), entry6_cin, 152, 64);
  gtk_widget_set_size_request (entry6_cin, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6_cin), 8226);

  button9_annuler = gtk_button_new ();
  gtk_widget_show (button9_annuler);
  gtk_fixed_put (GTK_FIXED (fixed3), button9_annuler, 232, 160);
  gtk_widget_set_size_request (button9_annuler, 80, 29);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button9_annuler), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox9), label18, FALSE, FALSE, 0);

  commentaire = gtk_label_new ("");
  gtk_widget_show (commentaire);
  gtk_fixed_put (GTK_FIXED (fixed3), commentaire, 96, 112);
  gtk_widget_set_size_request (commentaire, 200, 24);

  valider10 = gtk_button_new ();
  gtk_widget_show (valider10);
  gtk_fixed_put (GTK_FIXED (fixed3), valider10, 96, 160);
  gtk_widget_set_size_request (valider10, 88, 29);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (valider10), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox8), label17, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button9_annuler, "clicked",
                    G_CALLBACK (on_button9_annuler_clicked),
                    NULL);
  g_signal_connect ((gpointer) valider10, "clicked",
                    G_CALLBACK (on_valider10_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifier, modifier, "modifier");
  GLADE_HOOKUP_OBJECT (modifier, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (modifier, label16_cin, "label16_cin");
  GLADE_HOOKUP_OBJECT (modifier, entry6_cin, "entry6_cin");
  GLADE_HOOKUP_OBJECT (modifier, button9_annuler, "button9_annuler");
  GLADE_HOOKUP_OBJECT (modifier, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (modifier, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (modifier, image9, "image9");
  GLADE_HOOKUP_OBJECT (modifier, label18, "label18");
  GLADE_HOOKUP_OBJECT (modifier, commentaire, "commentaire");
  GLADE_HOOKUP_OBJECT (modifier, valider10, "valider10");
  GLADE_HOOKUP_OBJECT (modifier, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (modifier, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (modifier, image8, "image8");
  GLADE_HOOKUP_OBJECT (modifier, label17, "label17");

  return modifier;
}

GtkWidget*
create_formulaire (void)
{
  GtkWidget *formulaire;
  GtkWidget *fixed4;
  GtkWidget *nom1;
  GtkWidget *prenom1;
  GtkWidget *fixed5;
  GtkObject *spinbutton8_adj;
  GtkWidget *spinbutton8;
  GtkWidget *fixed6;
  GtkWidget *entry_cin;
  GtkWidget *entry7_nom;
  GtkWidget *entry8_prenom;
  GtkWidget *entry9_cin;
  GtkObject *spinbutton7_adj;
  GtkWidget *spinbutton7;
  GtkObject *spinbutton9_adj;
  GtkWidget *spinbutton9;
  GtkObject *spinbutton10_adj;
  GtkWidget *spinbutton10;
  GtkObject *spinbutton11_adj;
  GtkWidget *spinbutton11;
  GtkObject *spinbutton12_adj;
  GtkWidget *spinbutton12;
  GtkObject *spinbutton13_adj;
  GtkWidget *spinbutton13;
  GtkWidget *entry10_adresse;
  GtkWidget *entry11_num;
  GtkWidget *annuler1;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label29;
  GtkWidget *valider1;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label28;
  GtkWidget *num1;
  GtkWidget *adresse1;
  GtkWidget *sexe1;
  GtkWidget *date_de_naissance1;
  GtkWidget *date_de_rerutement1;
  GtkWidget *combobox2;
  GtkWidget *labelcin1;
  GtkWidget *cin1;

  formulaire = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (formulaire), _("formulaire"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (formulaire), fixed4);

  nom1 = gtk_label_new (_("Nom"));
  gtk_widget_show (nom1);
  gtk_fixed_put (GTK_FIXED (fixed4), nom1, 32, 16);
  gtk_widget_set_size_request (nom1, 41, 17);

  prenom1 = gtk_label_new (_("Prenom"));
  gtk_widget_show (prenom1);
  gtk_fixed_put (GTK_FIXED (fixed4), prenom1, 24, 40);
  gtk_widget_set_size_request (prenom1, 72, 25);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_fixed_put (GTK_FIXED (fixed4), fixed5, 224, 72);
  gtk_widget_set_size_request (fixed5, 50, 50);

  spinbutton8_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton8 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton8_adj), 1, 0);
  gtk_widget_show (spinbutton8);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton8, 272, 104);
  gtk_widget_set_size_request (spinbutton8, 40, 24);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_fixed_put (GTK_FIXED (fixed4), fixed6, 152, 48);
  gtk_widget_set_size_request (fixed6, 50, 50);

  entry_cin = gtk_entry_new ();
  gtk_widget_show (entry_cin);
  gtk_fixed_put (GTK_FIXED (fixed6), entry_cin, 8, 32);
  gtk_widget_set_size_request (entry_cin, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_cin), 8226);

  entry7_nom = gtk_entry_new ();
  gtk_widget_show (entry7_nom);
  gtk_fixed_put (GTK_FIXED (fixed4), entry7_nom, 160, 8);
  gtk_widget_set_size_request (entry7_nom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7_nom), 8226);

  entry8_prenom = gtk_entry_new ();
  gtk_widget_show (entry8_prenom);
  gtk_fixed_put (GTK_FIXED (fixed4), entry8_prenom, 160, 40);
  gtk_widget_set_size_request (entry8_prenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8_prenom), 8226);

  entry9_cin = gtk_entry_new ();
  gtk_widget_show (entry9_cin);
  gtk_fixed_put (GTK_FIXED (fixed4), entry9_cin, 160, 120);
  gtk_widget_set_size_request (entry9_cin, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9_cin), 8226);

  spinbutton7_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton7 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton7_adj), 1, 0);
  gtk_widget_show (spinbutton7);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton7, 160, 152);
  gtk_widget_set_size_request (spinbutton7, 48, 24);

  spinbutton9_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton9 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton9_adj), 1, 0);
  gtk_widget_show (spinbutton9);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton9, 208, 152);
  gtk_widget_set_size_request (spinbutton9, 48, 24);

  spinbutton10_adj = gtk_adjustment_new (1, 1990, 2021, 1, 10, 10);
  spinbutton10 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton10_adj), 1, 0);
  gtk_widget_show (spinbutton10);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton10, 264, 152);
  gtk_widget_set_size_request (spinbutton10, 60, 27);

  spinbutton11_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton11 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton11_adj), 1, 0);
  gtk_widget_show (spinbutton11);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton11, 160, 184);
  gtk_widget_set_size_request (spinbutton11, 48, 24);

  spinbutton12_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton12 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton12_adj), 1, 0);
  gtk_widget_show (spinbutton12);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton12, 208, 184);
  gtk_widget_set_size_request (spinbutton12, 48, 24);

  spinbutton13_adj = gtk_adjustment_new (1, 1990, 2002, 1, 10, 10);
  spinbutton13 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton13_adj), 1, 0);
  gtk_widget_show (spinbutton13);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton13, 264, 184);
  gtk_widget_set_size_request (spinbutton13, 60, 27);

  entry10_adresse = gtk_entry_new ();
  gtk_widget_show (entry10_adresse);
  gtk_fixed_put (GTK_FIXED (fixed4), entry10_adresse, 168, 248);
  gtk_widget_set_size_request (entry10_adresse, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10_adresse), 8226);

  entry11_num = gtk_entry_new ();
  gtk_widget_show (entry11_num);
  gtk_fixed_put (GTK_FIXED (fixed4), entry11_num, 168, 280);
  gtk_widget_set_size_request (entry11_num, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry11_num), 8226);

  annuler1 = gtk_button_new ();
  gtk_widget_show (annuler1);
  gtk_fixed_put (GTK_FIXED (fixed4), annuler1, 232, 320);
  gtk_widget_set_size_request (annuler1, 88, 29);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (annuler1), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox11), label29, FALSE, FALSE, 0);

  valider1 = gtk_button_new ();
  gtk_widget_show (valider1);
  gtk_fixed_put (GTK_FIXED (fixed4), valider1, 104, 320);
  gtk_widget_set_size_request (valider1, 88, 29);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (valider1), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox10), label28, FALSE, FALSE, 0);

  num1 = gtk_label_new (_("Num de telephone"));
  gtk_widget_show (num1);
  gtk_fixed_put (GTK_FIXED (fixed4), num1, 16, 280);
  gtk_widget_set_size_request (num1, 128, 33);

  adresse1 = gtk_label_new (_("Adresse"));
  gtk_widget_show (adresse1);
  gtk_fixed_put (GTK_FIXED (fixed4), adresse1, 16, 248);
  gtk_widget_set_size_request (adresse1, 88, 25);

  sexe1 = gtk_label_new (_("Sexe"));
  gtk_widget_show (sexe1);
  gtk_fixed_put (GTK_FIXED (fixed4), sexe1, 32, 224);
  gtk_widget_set_size_request (sexe1, 49, 17);

  date_de_naissance1 = gtk_label_new (_("Date de naissance"));
  gtk_widget_show (date_de_naissance1);
  gtk_fixed_put (GTK_FIXED (fixed4), date_de_naissance1, 16, 184);
  gtk_widget_set_size_request (date_de_naissance1, 136, 24);

  date_de_rerutement1 = gtk_label_new (_("Date de rerutement"));
  gtk_widget_show (date_de_rerutement1);
  gtk_fixed_put (GTK_FIXED (fixed4), date_de_rerutement1, 16, 152);
  gtk_widget_set_size_request (date_de_rerutement1, 144, 25);

  combobox2 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2);
  gtk_fixed_put (GTK_FIXED (fixed4), combobox2, 168, 216);
  gtk_widget_set_size_request (combobox2, 150, 30);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("homme"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("femme"));

  labelcin1 = gtk_label_new (_("Cin"));
  gtk_widget_show (labelcin1);
  gtk_fixed_put (GTK_FIXED (fixed4), labelcin1, 32, 88);
  gtk_widget_set_size_request (labelcin1, 49, 17);

  cin1 = gtk_label_new (_("Nouvelle Cin"));
  gtk_widget_show (cin1);
  gtk_fixed_put (GTK_FIXED (fixed4), cin1, 16, 120);
  gtk_widget_set_size_request (cin1, 104, 25);

  g_signal_connect ((gpointer) annuler1, "clicked",
                    G_CALLBACK (on_annuler1_clicked),
                    NULL);
  g_signal_connect ((gpointer) valider1, "clicked",
                    G_CALLBACK (on_valider1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (formulaire, formulaire, "formulaire");
  GLADE_HOOKUP_OBJECT (formulaire, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (formulaire, nom1, "nom1");
  GLADE_HOOKUP_OBJECT (formulaire, prenom1, "prenom1");
  GLADE_HOOKUP_OBJECT (formulaire, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (formulaire, spinbutton8, "spinbutton8");
  GLADE_HOOKUP_OBJECT (formulaire, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (formulaire, entry_cin, "entry_cin");
  GLADE_HOOKUP_OBJECT (formulaire, entry7_nom, "entry7_nom");
  GLADE_HOOKUP_OBJECT (formulaire, entry8_prenom, "entry8_prenom");
  GLADE_HOOKUP_OBJECT (formulaire, entry9_cin, "entry9_cin");
  GLADE_HOOKUP_OBJECT (formulaire, spinbutton7, "spinbutton7");
  GLADE_HOOKUP_OBJECT (formulaire, spinbutton9, "spinbutton9");
  GLADE_HOOKUP_OBJECT (formulaire, spinbutton10, "spinbutton10");
  GLADE_HOOKUP_OBJECT (formulaire, spinbutton11, "spinbutton11");
  GLADE_HOOKUP_OBJECT (formulaire, spinbutton12, "spinbutton12");
  GLADE_HOOKUP_OBJECT (formulaire, spinbutton13, "spinbutton13");
  GLADE_HOOKUP_OBJECT (formulaire, entry10_adresse, "entry10_adresse");
  GLADE_HOOKUP_OBJECT (formulaire, entry11_num, "entry11_num");
  GLADE_HOOKUP_OBJECT (formulaire, annuler1, "annuler1");
  GLADE_HOOKUP_OBJECT (formulaire, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (formulaire, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (formulaire, image11, "image11");
  GLADE_HOOKUP_OBJECT (formulaire, label29, "label29");
  GLADE_HOOKUP_OBJECT (formulaire, valider1, "valider1");
  GLADE_HOOKUP_OBJECT (formulaire, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (formulaire, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (formulaire, image10, "image10");
  GLADE_HOOKUP_OBJECT (formulaire, label28, "label28");
  GLADE_HOOKUP_OBJECT (formulaire, num1, "num1");
  GLADE_HOOKUP_OBJECT (formulaire, adresse1, "adresse1");
  GLADE_HOOKUP_OBJECT (formulaire, sexe1, "sexe1");
  GLADE_HOOKUP_OBJECT (formulaire, date_de_naissance1, "date_de_naissance1");
  GLADE_HOOKUP_OBJECT (formulaire, date_de_rerutement1, "date_de_rerutement1");
  GLADE_HOOKUP_OBJECT (formulaire, combobox2, "combobox2");
  GLADE_HOOKUP_OBJECT (formulaire, labelcin1, "labelcin1");
  GLADE_HOOKUP_OBJECT (formulaire, cin1, "cin1");

  return formulaire;
}

GtkWidget*
create_chercher (void)
{
  GtkWidget *chercher;
  GtkWidget *fixed7;
  GtkWidget *cin2;
  GtkWidget *entry12_cin;
  GtkWidget *chercher1;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label31;
  GtkWidget *annuler_chercher;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label32;
  GtkWidget *commentaire2;

  chercher = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (chercher), _("chercher"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (chercher), fixed7);

  cin2 = gtk_label_new (_("Cin"));
  gtk_widget_show (cin2);
  gtk_fixed_put (GTK_FIXED (fixed7), cin2, 48, 40);
  gtk_widget_set_size_request (cin2, 49, 17);

  entry12_cin = gtk_entry_new ();
  gtk_widget_show (entry12_cin);
  gtk_fixed_put (GTK_FIXED (fixed7), entry12_cin, 136, 32);
  gtk_widget_set_size_request (entry12_cin, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry12_cin), 8226);

  chercher1 = gtk_button_new ();
  gtk_widget_show (chercher1);
  gtk_fixed_put (GTK_FIXED (fixed7), chercher1, 80, 104);
  gtk_widget_set_size_request (chercher1, 96, 29);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (chercher1), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label31 = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (label31);
  gtk_box_pack_start (GTK_BOX (hbox12), label31, FALSE, FALSE, 0);

  annuler_chercher = gtk_button_new ();
  gtk_widget_show (annuler_chercher);
  gtk_fixed_put (GTK_FIXED (fixed7), annuler_chercher, 224, 104);
  gtk_widget_set_size_request (annuler_chercher, 80, 29);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (annuler_chercher), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label32 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox13), label32, FALSE, FALSE, 0);

  commentaire2 = gtk_label_new ("");
  gtk_widget_show (commentaire2);
  gtk_fixed_put (GTK_FIXED (fixed7), commentaire2, 56, 72);
  gtk_widget_set_size_request (commentaire2, 232, 24);

  g_signal_connect ((gpointer) chercher1, "clicked",
                    G_CALLBACK (on_chercher1_clicked),
                    NULL);
  g_signal_connect ((gpointer) annuler_chercher, "clicked",
                    G_CALLBACK (on_annuler_chercher_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (chercher, chercher, "chercher");
  GLADE_HOOKUP_OBJECT (chercher, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (chercher, cin2, "cin2");
  GLADE_HOOKUP_OBJECT (chercher, entry12_cin, "entry12_cin");
  GLADE_HOOKUP_OBJECT (chercher, chercher1, "chercher1");
  GLADE_HOOKUP_OBJECT (chercher, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (chercher, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (chercher, image12, "image12");
  GLADE_HOOKUP_OBJECT (chercher, label31, "label31");
  GLADE_HOOKUP_OBJECT (chercher, annuler_chercher, "annuler_chercher");
  GLADE_HOOKUP_OBJECT (chercher, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (chercher, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (chercher, image13, "image13");
  GLADE_HOOKUP_OBJECT (chercher, label32, "label32");
  GLADE_HOOKUP_OBJECT (chercher, commentaire2, "commentaire2");

  return chercher;
}

GtkWidget*
create_afficher (void)
{
  GtkWidget *afficher;
  GtkWidget *fixed8;
  GtkWidget *treeview1;
  GtkWidget *annuler_afficher;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label34;
  GtkWidget *la_liste_des_ouvriers;

  afficher = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (afficher), _("afficher"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (afficher), fixed8);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed8), treeview1, 24, 40);
  gtk_widget_set_size_request (treeview1, 864, 208);

  annuler_afficher = gtk_button_new ();
  gtk_widget_show (annuler_afficher);
  gtk_fixed_put (GTK_FIXED (fixed8), annuler_afficher, 104, 256);
  gtk_widget_set_size_request (annuler_afficher, 96, 29);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (annuler_afficher), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label34 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (hbox14), label34, FALSE, FALSE, 0);

  la_liste_des_ouvriers = gtk_label_new (_("la liste des ouvriers"));
  gtk_widget_show (la_liste_des_ouvriers);
  gtk_fixed_put (GTK_FIXED (fixed8), la_liste_des_ouvriers, 16, 16);
  gtk_widget_set_size_request (la_liste_des_ouvriers, 160, 17);

  g_signal_connect ((gpointer) annuler_afficher, "clicked",
                    G_CALLBACK (on_annuler_afficher_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (afficher, afficher, "afficher");
  GLADE_HOOKUP_OBJECT (afficher, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (afficher, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (afficher, annuler_afficher, "annuler_afficher");
  GLADE_HOOKUP_OBJECT (afficher, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (afficher, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (afficher, image14, "image14");
  GLADE_HOOKUP_OBJECT (afficher, label34, "label34");
  GLADE_HOOKUP_OBJECT (afficher, la_liste_des_ouvriers, "la_liste_des_ouvriers");

  return afficher;
}

GtkWidget*
create_supprimer (void)
{
  GtkWidget *supprimer;
  GtkWidget *fixed9;
  GtkWidget *entry13_cin;
  GtkWidget *cin_supprimer;
  GtkWidget *supprimer1;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label36;
  GtkWidget *commentaire1;
  GtkWidget *annuler_supprimer;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label37;

  supprimer = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (supprimer), _("supprimer"));

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (supprimer), fixed9);

  entry13_cin = gtk_entry_new ();
  gtk_widget_show (entry13_cin);
  gtk_fixed_put (GTK_FIXED (fixed9), entry13_cin, 160, 56);
  gtk_widget_set_size_request (entry13_cin, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry13_cin), 8226);

  cin_supprimer = gtk_label_new (_("Cin"));
  gtk_widget_show (cin_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed9), cin_supprimer, 64, 64);
  gtk_widget_set_size_request (cin_supprimer, 49, 17);

  supprimer1 = gtk_button_new ();
  gtk_widget_show (supprimer1);
  gtk_fixed_put (GTK_FIXED (fixed9), supprimer1, 56, 152);
  gtk_widget_set_size_request (supprimer1, 104, 29);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (supprimer1), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label36 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox15), label36, FALSE, FALSE, 0);

  commentaire1 = gtk_label_new ("");
  gtk_widget_show (commentaire1);
  gtk_fixed_put (GTK_FIXED (fixed9), commentaire1, 56, 104);
  gtk_widget_set_size_request (commentaire1, 248, 25);

  annuler_supprimer = gtk_button_new ();
  gtk_widget_show (annuler_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed9), annuler_supprimer, 224, 152);
  gtk_widget_set_size_request (annuler_supprimer, 88, 29);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (annuler_supprimer), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label37 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label37);
  gtk_box_pack_start (GTK_BOX (hbox16), label37, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) supprimer1, "clicked",
                    G_CALLBACK (on_supprimer1_clicked),
                    NULL);
  g_signal_connect ((gpointer) annuler_supprimer, "clicked",
                    G_CALLBACK (on_annuler_supprimer_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (supprimer, supprimer, "supprimer");
  GLADE_HOOKUP_OBJECT (supprimer, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (supprimer, entry13_cin, "entry13_cin");
  GLADE_HOOKUP_OBJECT (supprimer, cin_supprimer, "cin_supprimer");
  GLADE_HOOKUP_OBJECT (supprimer, supprimer1, "supprimer1");
  GLADE_HOOKUP_OBJECT (supprimer, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (supprimer, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (supprimer, image15, "image15");
  GLADE_HOOKUP_OBJECT (supprimer, label36, "label36");
  GLADE_HOOKUP_OBJECT (supprimer, commentaire1, "commentaire1");
  GLADE_HOOKUP_OBJECT (supprimer, annuler_supprimer, "annuler_supprimer");
  GLADE_HOOKUP_OBJECT (supprimer, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (supprimer, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (supprimer, image16, "image16");
  GLADE_HOOKUP_OBJECT (supprimer, label37, "label37");

  return supprimer;
}

GtkWidget*
create_affichage (void)
{
  GtkWidget *affichage;
  GtkWidget *fixed10;
  GtkWidget *treeview2;
  GtkWidget *annuler10;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image17;
  GtkWidget *label41;

  affichage = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (affichage), _("affichage"));

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (affichage), fixed10);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed10), treeview2, 8, 24);
  gtk_widget_set_size_request (treeview2, 760, 96);

  annuler10 = gtk_button_new ();
  gtk_widget_show (annuler10);
  gtk_fixed_put (GTK_FIXED (fixed10), annuler10, 160, 192);
  gtk_widget_set_size_request (annuler10, 80, 32);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (annuler10), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image17 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox17), image17, FALSE, FALSE, 0);

  label41 = gtk_label_new_with_mnemonic (_("annuler"));
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox17), label41, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) annuler10, "clicked",
                    G_CALLBACK (on_annuler10_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (affichage, affichage, "affichage");
  GLADE_HOOKUP_OBJECT (affichage, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (affichage, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (affichage, annuler10, "annuler10");
  GLADE_HOOKUP_OBJECT (affichage, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (affichage, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (affichage, image17, "image17");
  GLADE_HOOKUP_OBJECT (affichage, label41, "label41");

  return affichage;
}

GtkWidget*
create_absenteisme (void)
{
  GtkWidget *absenteisme;
  GtkWidget *fixed11;
  GtkWidget *entrycinabs;
  GtkWidget *jour_abs;
  GtkWidget *mois_abs;
  GtkWidget *annee_abs;
  GtkWidget *valeur;
  GtkObject *spinbuttonjour_adj;
  GtkWidget *spinbuttonjour;
  GtkObject *spinbuttonmois_adj;
  GtkWidget *spinbuttonmois;
  GtkObject *spinbuttonannee_adj;
  GtkWidget *spinbuttonannee;
  GtkObject *spinbuttonvaleur_adj;
  GtkWidget *spinbuttonvaleur;
  GtkWidget *annuler_abs;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image18;
  GtkWidget *label47;
  GtkWidget *valider_abs;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image19;
  GtkWidget *label48;
  GtkWidget *cin_abs;

  absenteisme = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (absenteisme), _("absenteisme"));

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (absenteisme), fixed11);

  entrycinabs = gtk_entry_new ();
  gtk_widget_show (entrycinabs);
  gtk_fixed_put (GTK_FIXED (fixed11), entrycinabs, 184, 16);
  gtk_widget_set_size_request (entrycinabs, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrycinabs), 8226);

  jour_abs = gtk_label_new (_("jour"));
  gtk_widget_show (jour_abs);
  gtk_fixed_put (GTK_FIXED (fixed11), jour_abs, 40, 64);
  gtk_widget_set_size_request (jour_abs, 49, 17);

  mois_abs = gtk_label_new (_("mois"));
  gtk_widget_show (mois_abs);
  gtk_fixed_put (GTK_FIXED (fixed11), mois_abs, 40, 104);
  gtk_widget_set_size_request (mois_abs, 49, 17);

  annee_abs = gtk_label_new (_("annee"));
  gtk_widget_show (annee_abs);
  gtk_fixed_put (GTK_FIXED (fixed11), annee_abs, 40, 144);
  gtk_widget_set_size_request (annee_abs, 49, 17);

  valeur = gtk_label_new (_("valeur"));
  gtk_widget_show (valeur);
  gtk_fixed_put (GTK_FIXED (fixed11), valeur, 40, 184);
  gtk_widget_set_size_request (valeur, 49, 17);

  spinbuttonjour_adj = gtk_adjustment_new (1, 1, 30, 1, 10, 10);
  spinbuttonjour = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonjour_adj), 1, 0);
  gtk_widget_show (spinbuttonjour);
  gtk_fixed_put (GTK_FIXED (fixed11), spinbuttonjour, 184, 56);
  gtk_widget_set_size_request (spinbuttonjour, 60, 27);

  spinbuttonmois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbuttonmois = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonmois_adj), 1, 0);
  gtk_widget_show (spinbuttonmois);
  gtk_fixed_put (GTK_FIXED (fixed11), spinbuttonmois, 184, 96);
  gtk_widget_set_size_request (spinbuttonmois, 60, 27);

  spinbuttonannee_adj = gtk_adjustment_new (1, 1990, 2030, 1, 10, 10);
  spinbuttonannee = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonannee_adj), 1, 0);
  gtk_widget_show (spinbuttonannee);
  gtk_fixed_put (GTK_FIXED (fixed11), spinbuttonannee, 184, 136);
  gtk_widget_set_size_request (spinbuttonannee, 60, 27);

  spinbuttonvaleur_adj = gtk_adjustment_new (1, 0, 1, 1, 10, 10);
  spinbuttonvaleur = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonvaleur_adj), 1, 0);
  gtk_widget_show (spinbuttonvaleur);
  gtk_fixed_put (GTK_FIXED (fixed11), spinbuttonvaleur, 184, 184);
  gtk_widget_set_size_request (spinbuttonvaleur, 60, 27);

  annuler_abs = gtk_button_new ();
  gtk_widget_show (annuler_abs);
  gtk_fixed_put (GTK_FIXED (fixed11), annuler_abs, 216, 256);
  gtk_widget_set_size_request (annuler_abs, 96, 29);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (annuler_abs), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image18 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox18), image18, FALSE, FALSE, 0);

  label47 = gtk_label_new_with_mnemonic (_("annuler"));
  gtk_widget_show (label47);
  gtk_box_pack_start (GTK_BOX (hbox18), label47, FALSE, FALSE, 0);

  valider_abs = gtk_button_new ();
  gtk_widget_show (valider_abs);
  gtk_fixed_put (GTK_FIXED (fixed11), valider_abs, 80, 256);
  gtk_widget_set_size_request (valider_abs, 80, 29);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (valider_abs), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image19 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox19), image19, FALSE, FALSE, 0);

  label48 = gtk_label_new_with_mnemonic (_("valider"));
  gtk_widget_show (label48);
  gtk_box_pack_start (GTK_BOX (hbox19), label48, FALSE, FALSE, 0);

  cin_abs = gtk_label_new (_("cin"));
  gtk_widget_show (cin_abs);
  gtk_fixed_put (GTK_FIXED (fixed11), cin_abs, 40, 24);
  gtk_widget_set_size_request (cin_abs, 49, 17);

  g_signal_connect ((gpointer) annuler_abs, "clicked",
                    G_CALLBACK (on_annuler_abs_clicked),
                    NULL);
  g_signal_connect ((gpointer) valider_abs, "clicked",
                    G_CALLBACK (on_valider_abs_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (absenteisme, absenteisme, "absenteisme");
  GLADE_HOOKUP_OBJECT (absenteisme, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (absenteisme, entrycinabs, "entrycinabs");
  GLADE_HOOKUP_OBJECT (absenteisme, jour_abs, "jour_abs");
  GLADE_HOOKUP_OBJECT (absenteisme, mois_abs, "mois_abs");
  GLADE_HOOKUP_OBJECT (absenteisme, annee_abs, "annee_abs");
  GLADE_HOOKUP_OBJECT (absenteisme, valeur, "valeur");
  GLADE_HOOKUP_OBJECT (absenteisme, spinbuttonjour, "spinbuttonjour");
  GLADE_HOOKUP_OBJECT (absenteisme, spinbuttonmois, "spinbuttonmois");
  GLADE_HOOKUP_OBJECT (absenteisme, spinbuttonannee, "spinbuttonannee");
  GLADE_HOOKUP_OBJECT (absenteisme, spinbuttonvaleur, "spinbuttonvaleur");
  GLADE_HOOKUP_OBJECT (absenteisme, annuler_abs, "annuler_abs");
  GLADE_HOOKUP_OBJECT (absenteisme, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (absenteisme, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (absenteisme, image18, "image18");
  GLADE_HOOKUP_OBJECT (absenteisme, label47, "label47");
  GLADE_HOOKUP_OBJECT (absenteisme, valider_abs, "valider_abs");
  GLADE_HOOKUP_OBJECT (absenteisme, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (absenteisme, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (absenteisme, image19, "image19");
  GLADE_HOOKUP_OBJECT (absenteisme, label48, "label48");
  GLADE_HOOKUP_OBJECT (absenteisme, cin_abs, "cin_abs");

  return absenteisme;
}

GtkWidget*
create_surface_absenteisme (void)
{
  GtkWidget *surface_absenteisme;
  GtkWidget *fixed14;
  GtkObject *spinbuttonannee1_adj;
  GtkWidget *spinbuttonannee1;
  GtkWidget *annee_sur1;
  GtkWidget *meilleur;
  GtkWidget *mois_taux;
  GtkWidget *annee_taux;
  GtkObject *spinbuttonmois1_adj;
  GtkWidget *spinbuttonmois1;
  GtkObject *spinbuttonannee2_adj;
  GtkWidget *spinbuttonannee2;
  GtkWidget *valider_sur1;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image20;
  GtkWidget *label50;
  GtkWidget *valider_taux;
  GtkWidget *alignment21;
  GtkWidget *hbox21;
  GtkWidget *image21;
  GtkWidget *label56;
  GtkWidget *label_taux;
  GtkWidget *labeltaux;
  GtkWidget *labelmeilleur;
  GtkWidget *annulersur;
  GtkWidget *alignment24;
  GtkWidget *hbox24;
  GtkWidget *image24;
  GtkWidget *label59;

  surface_absenteisme = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (surface_absenteisme), _("surface_absenteisme"));

  fixed14 = gtk_fixed_new ();
  gtk_widget_show (fixed14);
  gtk_container_add (GTK_CONTAINER (surface_absenteisme), fixed14);

  spinbuttonannee1_adj = gtk_adjustment_new (1990, 1990, 2030, 1, 10, 10);
  spinbuttonannee1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonannee1_adj), 1, 0);
  gtk_widget_show (spinbuttonannee1);
  gtk_fixed_put (GTK_FIXED (fixed14), spinbuttonannee1, 240, 40);
  gtk_widget_set_size_request (spinbuttonannee1, 80, 27);

  annee_sur1 = gtk_label_new (_("annee"));
  gtk_widget_show (annee_sur1);
  gtk_fixed_put (GTK_FIXED (fixed14), annee_sur1, 96, 48);
  gtk_widget_set_size_request (annee_sur1, 56, 17);

  meilleur = gtk_label_new (_("meilleur ouvrier"));
  gtk_widget_show (meilleur);
  gtk_fixed_put (GTK_FIXED (fixed14), meilleur, 40, 144);
  gtk_widget_set_size_request (meilleur, 136, 24);

  mois_taux = gtk_label_new (_("mois"));
  gtk_widget_show (mois_taux);
  gtk_fixed_put (GTK_FIXED (fixed14), mois_taux, 64, 192);
  gtk_widget_set_size_request (mois_taux, 49, 17);

  annee_taux = gtk_label_new (_("annee"));
  gtk_widget_show (annee_taux);
  gtk_fixed_put (GTK_FIXED (fixed14), annee_taux, 64, 224);
  gtk_widget_set_size_request (annee_taux, 49, 17);

  spinbuttonmois1_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbuttonmois1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonmois1_adj), 1, 0);
  gtk_widget_show (spinbuttonmois1);
  gtk_fixed_put (GTK_FIXED (fixed14), spinbuttonmois1, 176, 184);
  gtk_widget_set_size_request (spinbuttonmois1, 60, 27);

  spinbuttonannee2_adj = gtk_adjustment_new (1, 1990, 2030, 1, 10, 10);
  spinbuttonannee2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonannee2_adj), 1, 0);
  gtk_widget_show (spinbuttonannee2);
  gtk_fixed_put (GTK_FIXED (fixed14), spinbuttonannee2, 176, 224);
  gtk_widget_set_size_request (spinbuttonannee2, 60, 27);

  valider_sur1 = gtk_button_new ();
  gtk_widget_show (valider_sur1);
  gtk_fixed_put (GTK_FIXED (fixed14), valider_sur1, 168, 96);
  gtk_widget_set_size_request (valider_sur1, 80, 29);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (valider_sur1), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image20 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox20), image20, FALSE, FALSE, 0);

  label50 = gtk_label_new_with_mnemonic (_("valider"));
  gtk_widget_show (label50);
  gtk_box_pack_start (GTK_BOX (hbox20), label50, FALSE, FALSE, 0);

  valider_taux = gtk_button_new ();
  gtk_widget_show (valider_taux);
  gtk_fixed_put (GTK_FIXED (fixed14), valider_taux, 168, 264);
  gtk_widget_set_size_request (valider_taux, 80, 29);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (valider_taux), alignment21);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox21);

  image21 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox21), image21, FALSE, FALSE, 0);

  label56 = gtk_label_new_with_mnemonic (_("valider"));
  gtk_widget_show (label56);
  gtk_box_pack_start (GTK_BOX (hbox21), label56, FALSE, FALSE, 0);

  label_taux = gtk_label_new (_("taux d'absenteisme"));
  gtk_widget_show (label_taux);
  gtk_fixed_put (GTK_FIXED (fixed14), label_taux, 48, 304);
  gtk_widget_set_size_request (label_taux, 160, 24);

  labeltaux = gtk_label_new ("");
  gtk_widget_show (labeltaux);
  gtk_fixed_put (GTK_FIXED (fixed14), labeltaux, 264, 304);
  gtk_widget_set_size_request (labeltaux, 160, 24);

  labelmeilleur = gtk_label_new ("");
  gtk_widget_show (labelmeilleur);
  gtk_fixed_put (GTK_FIXED (fixed14), labelmeilleur, 264, 144);
  gtk_widget_set_size_request (labelmeilleur, 144, 25);

  annulersur = gtk_button_new ();
  gtk_widget_show (annulersur);
  gtk_fixed_put (GTK_FIXED (fixed14), annulersur, 168, 352);
  gtk_widget_set_size_request (annulersur, 80, 29);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (annulersur), alignment24);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox24);

  image24 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox24), image24, FALSE, FALSE, 0);

  label59 = gtk_label_new_with_mnemonic (_("annuler"));
  gtk_widget_show (label59);
  gtk_box_pack_start (GTK_BOX (hbox24), label59, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) valider_sur1, "clicked",
                    G_CALLBACK (on_valider_sur1_clicked),
                    NULL);
  g_signal_connect ((gpointer) valider_taux, "clicked",
                    G_CALLBACK (on_valider_taux_clicked),
                    NULL);
  g_signal_connect ((gpointer) annulersur, "clicked",
                    G_CALLBACK (on_annulersur_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (surface_absenteisme, surface_absenteisme, "surface_absenteisme");
  GLADE_HOOKUP_OBJECT (surface_absenteisme, fixed14, "fixed14");
  GLADE_HOOKUP_OBJECT (surface_absenteisme, spinbuttonannee1, "spinbuttonannee1");
  GLADE_HOOKUP_OBJECT (surface_absenteisme, annee_sur1, "annee_sur1");
  GLADE_HOOKUP_OBJECT (surface_absenteisme, meilleur, "meilleur");
  GLADE_HOOKUP_OBJECT (surface_absenteisme, mois_taux, "mois_taux");
  GLADE_HOOKUP_OBJECT (surface_absenteisme, annee_taux, "annee_taux");
  GLADE_HOOKUP_OBJECT (surface_absenteisme, spinbuttonmois1, "spinbuttonmois1");
  GLADE_HOOKUP_OBJECT (surface_absenteisme, spinbuttonannee2, "spinbuttonannee2");
  GLADE_HOOKUP_OBJECT (surface_absenteisme, valider_sur1, "valider_sur1");
  GLADE_HOOKUP_OBJECT (surface_absenteisme, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (surface_absenteisme, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (surface_absenteisme, image20, "image20");
  GLADE_HOOKUP_OBJECT (surface_absenteisme, label50, "label50");
  GLADE_HOOKUP_OBJECT (surface_absenteisme, valider_taux, "valider_taux");
  GLADE_HOOKUP_OBJECT (surface_absenteisme, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (surface_absenteisme, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (surface_absenteisme, image21, "image21");
  GLADE_HOOKUP_OBJECT (surface_absenteisme, label56, "label56");
  GLADE_HOOKUP_OBJECT (surface_absenteisme, label_taux, "label_taux");
  GLADE_HOOKUP_OBJECT (surface_absenteisme, labeltaux, "labeltaux");
  GLADE_HOOKUP_OBJECT (surface_absenteisme, labelmeilleur, "labelmeilleur");
  GLADE_HOOKUP_OBJECT (surface_absenteisme, annulersur, "annulersur");
  GLADE_HOOKUP_OBJECT (surface_absenteisme, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (surface_absenteisme, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (surface_absenteisme, image24, "image24");
  GLADE_HOOKUP_OBJECT (surface_absenteisme, label59, "label59");

  return surface_absenteisme;
}

