/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Gestion_des_equipements_agricoles (void);
GtkWidget* create_Ajouter (void);
GtkWidget* create_Modifier (void);
GtkWidget* create_Supprimer (void);
GtkWidget* create_Chercher (void);
GtkWidget* create_Formulaire (void);
GtkWidget* create_Afficher (void);
GtkWidget* create_Affichage (void);
