/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Gestion_des_equipements_agricoles (void)
{
  GtkWidget *Gestion_des_equipements_agricoles;
  GtkWidget *fixed1;
  GtkWidget *modifier;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label2;
  GtkWidget *supprimer;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label4;
  GtkWidget *ajouter;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label1;
  GtkWidget *chercher;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label3;
  GtkWidget *afficher;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label15;

  Gestion_des_equipements_agricoles = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Gestion_des_equipements_agricoles), _("Gestion des \303\251quipements agricoles"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (Gestion_des_equipements_agricoles), fixed1);

  modifier = gtk_toggle_button_new ();
  gtk_widget_show (modifier);
  gtk_fixed_put (GTK_FIXED (fixed1), modifier, 392, 80);
  gtk_widget_set_size_request (modifier, 109, 29);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (modifier), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox2), label2, FALSE, FALSE, 0);

  supprimer = gtk_toggle_button_new ();
  gtk_widget_show (supprimer);
  gtk_fixed_put (GTK_FIXED (fixed1), supprimer, 392, 168);
  gtk_widget_set_size_request (supprimer, 109, 29);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (supprimer), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox4), label4, FALSE, FALSE, 0);

  ajouter = gtk_toggle_button_new ();
  gtk_widget_show (ajouter);
  gtk_fixed_put (GTK_FIXED (fixed1), ajouter, 168, 80);
  gtk_widget_set_size_request (ajouter, 109, 29);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (ajouter), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);

  chercher = gtk_toggle_button_new ();
  gtk_widget_show (chercher);
  gtk_fixed_put (GTK_FIXED (fixed1), chercher, 168, 168);
  gtk_widget_set_size_request (chercher, 109, 29);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (chercher), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox3), label3, FALSE, FALSE, 0);

  afficher = gtk_toggle_button_new ();
  gtk_widget_show (afficher);
  gtk_fixed_put (GTK_FIXED (fixed1), afficher, 280, 240);
  gtk_widget_set_size_request (afficher, 109, 29);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (afficher), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-print-preview", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox15), label15, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) modifier, "clicked",
                    G_CALLBACK (on_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimer, "clicked",
                    G_CALLBACK (on_supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouter, "clicked",
                    G_CALLBACK (on_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) chercher, "clicked",
                    G_CALLBACK (on_chercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) afficher, "clicked",
                    G_CALLBACK (on_afficher_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Gestion_des_equipements_agricoles, Gestion_des_equipements_agricoles, "Gestion_des_equipements_agricoles");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements_agricoles, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements_agricoles, modifier, "modifier");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements_agricoles, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements_agricoles, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements_agricoles, image2, "image2");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements_agricoles, label2, "label2");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements_agricoles, supprimer, "supprimer");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements_agricoles, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements_agricoles, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements_agricoles, image4, "image4");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements_agricoles, label4, "label4");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements_agricoles, ajouter, "ajouter");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements_agricoles, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements_agricoles, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements_agricoles, image1, "image1");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements_agricoles, label1, "label1");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements_agricoles, chercher, "chercher");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements_agricoles, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements_agricoles, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements_agricoles, image3, "image3");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements_agricoles, label3, "label3");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements_agricoles, afficher, "afficher");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements_agricoles, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements_agricoles, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements_agricoles, image15, "image15");
  GLADE_HOOKUP_OBJECT (Gestion_des_equipements_agricoles, label15, "label15");

  return Gestion_des_equipements_agricoles;
}

GtkWidget*
create_Ajouter (void)
{
  GtkWidget *Ajouter;
  GtkWidget *fixed2;
  GtkWidget *entry1_nom;
  GtkWidget *entry2_numero;
  GtkWidget *entry4_cout;
  GtkObject *jour_adj;
  GtkWidget *jour;
  GtkObject *mois_adj;
  GtkWidget *mois;
  GtkObject *annee_adj;
  GtkWidget *annee;
  GtkObject *entry5_duree_adj;
  GtkWidget *entry5_duree;
  GtkWidget *cout;
  GtkWidget *numero;
  GtkWidget *nom;
  GtkWidget *marque;
  GtkWidget *date;
  GtkWidget *duree;
  GtkWidget *enregistrer1;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label5;
  GtkWidget *entry3_marque;
  GtkWidget *annuler1;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label6;
  GtkWidget *label18;

  Ajouter = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Ajouter), _("Ajouter"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (Ajouter), fixed2);

  entry1_nom = gtk_entry_new ();
  gtk_widget_show (entry1_nom);
  gtk_fixed_put (GTK_FIXED (fixed2), entry1_nom, 232, 72);
  gtk_widget_set_size_request (entry1_nom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1_nom), 8226);

  entry2_numero = gtk_entry_new ();
  gtk_widget_show (entry2_numero);
  gtk_fixed_put (GTK_FIXED (fixed2), entry2_numero, 232, 32);
  gtk_widget_set_size_request (entry2_numero, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2_numero), 8226);

  entry4_cout = gtk_entry_new ();
  gtk_widget_show (entry4_cout);
  gtk_fixed_put (GTK_FIXED (fixed2), entry4_cout, 232, 152);
  gtk_widget_set_size_request (entry4_cout, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4_cout), 8226);

  jour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  jour = gtk_spin_button_new (GTK_ADJUSTMENT (jour_adj), 1, 0);
  gtk_widget_show (jour);
  gtk_fixed_put (GTK_FIXED (fixed2), jour, 232, 192);
  gtk_widget_set_size_request (jour, 60, 27);

  mois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  mois = gtk_spin_button_new (GTK_ADJUSTMENT (mois_adj), 1, 0);
  gtk_widget_show (mois);
  gtk_fixed_put (GTK_FIXED (fixed2), mois, 296, 192);
  gtk_widget_set_size_request (mois, 60, 27);

  annee_adj = gtk_adjustment_new (1990, 1990, 2020, 1, 10, 10);
  annee = gtk_spin_button_new (GTK_ADJUSTMENT (annee_adj), 1, 0);
  gtk_widget_show (annee);
  gtk_fixed_put (GTK_FIXED (fixed2), annee, 360, 192);
  gtk_widget_set_size_request (annee, 60, 27);

  entry5_duree_adj = gtk_adjustment_new (1, 0, 4000, 1, 10, 10);
  entry5_duree = gtk_spin_button_new (GTK_ADJUSTMENT (entry5_duree_adj), 1, 0);
  gtk_widget_show (entry5_duree);
  gtk_fixed_put (GTK_FIXED (fixed2), entry5_duree, 232, 232);
  gtk_widget_set_size_request (entry5_duree, 60, 27);

  cout = gtk_label_new (_("Le cout d'achat"));
  gtk_widget_show (cout);
  gtk_fixed_put (GTK_FIXED (fixed2), cout, 8, 160);
  gtk_widget_set_size_request (cout, 144, 24);

  numero = gtk_label_new (_("Num\303\251ro de la machine"));
  gtk_widget_show (numero);
  gtk_fixed_put (GTK_FIXED (fixed2), numero, 24, 24);
  gtk_widget_set_size_request (numero, 160, 41);

  nom = gtk_label_new (_("Nom de l'\303\251quipement"));
  gtk_widget_show (nom);
  gtk_fixed_put (GTK_FIXED (fixed2), nom, 16, 72);
  gtk_widget_set_size_request (nom, 176, 33);

  marque = gtk_label_new (_("Marque"));
  gtk_widget_show (marque);
  gtk_fixed_put (GTK_FIXED (fixed2), marque, 0, 112);
  gtk_widget_set_size_request (marque, 112, 48);

  date = gtk_label_new (_("La date d'achat"));
  gtk_widget_show (date);
  gtk_fixed_put (GTK_FIXED (fixed2), date, 16, 192);
  gtk_widget_set_size_request (date, 128, 33);

  duree = gtk_label_new (_("La dur\303\251e de fonctionnement"));
  gtk_widget_show (duree);
  gtk_fixed_put (GTK_FIXED (fixed2), duree, 24, 232);
  gtk_widget_set_size_request (duree, 200, 32);

  enregistrer1 = gtk_toggle_button_new ();
  gtk_widget_show (enregistrer1);
  gtk_fixed_put (GTK_FIXED (fixed2), enregistrer1, 72, 280);
  gtk_widget_set_size_request (enregistrer1, 109, 29);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (enregistrer1), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Enregistrer"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox5), label5, FALSE, FALSE, 0);

  entry3_marque = gtk_combo_box_new_text ();
  gtk_widget_show (entry3_marque);
  gtk_fixed_put (GTK_FIXED (fixed2), entry3_marque, 231, 113);
  gtk_widget_set_size_request (entry3_marque, 163, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry3_marque), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry3_marque), _("JHON_DEERE"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry3_marque), _("NEW_HOLLAND"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry3_marque), _("FENDT"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry3_marque), _("MASSEY_FERGUSON"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry3_marque), _("CLAAS"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry3_marque), _("CASE_IH"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry3_marque), _("VALTRA"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry3_marque), _("KUBOTA"));

  annuler1 = gtk_toggle_button_new ();
  gtk_widget_show (annuler1);
  gtk_fixed_put (GTK_FIXED (fixed2), annuler1, 232, 280);
  gtk_widget_set_size_request (annuler1, 109, 29);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (annuler1), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("annuler"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox6), label6, FALSE, FALSE, 0);

  label18 = gtk_label_new (_("jours"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed2), label18, 304, 232);
  gtk_widget_set_size_request (label18, 64, 25);

  g_signal_connect ((gpointer) enregistrer1, "clicked",
                    G_CALLBACK (on_enregistrer1_clicked),
                    NULL);
  g_signal_connect ((gpointer) annuler1, "clicked",
                    G_CALLBACK (on_annuler1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Ajouter, Ajouter, "Ajouter");
  GLADE_HOOKUP_OBJECT (Ajouter, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (Ajouter, entry1_nom, "entry1_nom");
  GLADE_HOOKUP_OBJECT (Ajouter, entry2_numero, "entry2_numero");
  GLADE_HOOKUP_OBJECT (Ajouter, entry4_cout, "entry4_cout");
  GLADE_HOOKUP_OBJECT (Ajouter, jour, "jour");
  GLADE_HOOKUP_OBJECT (Ajouter, mois, "mois");
  GLADE_HOOKUP_OBJECT (Ajouter, annee, "annee");
  GLADE_HOOKUP_OBJECT (Ajouter, entry5_duree, "entry5_duree");
  GLADE_HOOKUP_OBJECT (Ajouter, cout, "cout");
  GLADE_HOOKUP_OBJECT (Ajouter, numero, "numero");
  GLADE_HOOKUP_OBJECT (Ajouter, nom, "nom");
  GLADE_HOOKUP_OBJECT (Ajouter, marque, "marque");
  GLADE_HOOKUP_OBJECT (Ajouter, date, "date");
  GLADE_HOOKUP_OBJECT (Ajouter, duree, "duree");
  GLADE_HOOKUP_OBJECT (Ajouter, enregistrer1, "enregistrer1");
  GLADE_HOOKUP_OBJECT (Ajouter, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (Ajouter, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (Ajouter, image5, "image5");
  GLADE_HOOKUP_OBJECT (Ajouter, label5, "label5");
  GLADE_HOOKUP_OBJECT (Ajouter, entry3_marque, "entry3_marque");
  GLADE_HOOKUP_OBJECT (Ajouter, annuler1, "annuler1");
  GLADE_HOOKUP_OBJECT (Ajouter, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (Ajouter, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (Ajouter, image6, "image6");
  GLADE_HOOKUP_OBJECT (Ajouter, label6, "label6");
  GLADE_HOOKUP_OBJECT (Ajouter, label18, "label18");

  return Ajouter;
}

GtkWidget*
create_Modifier (void)
{
  GtkWidget *Modifier;
  GtkWidget *fixed3;
  GtkWidget *modification_num;
  GtkWidget *enregistrer2;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label7;
  GtkWidget *annuler2;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label8;
  GtkWidget *modifier_num;
  GtkWidget *commentaire;

  Modifier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Modifier), _("Modifier"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (Modifier), fixed3);

  modification_num = gtk_entry_new ();
  gtk_widget_show (modification_num);
  gtk_fixed_put (GTK_FIXED (fixed3), modification_num, 112, 96);
  gtk_widget_set_size_request (modification_num, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (modification_num), 8226);

  enregistrer2 = gtk_toggle_button_new ();
  gtk_widget_show (enregistrer2);
  gtk_fixed_put (GTK_FIXED (fixed3), enregistrer2, 48, 184);
  gtk_widget_set_size_request (enregistrer2, 109, 29);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (enregistrer2), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("enregistrer"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox7), label7, FALSE, FALSE, 0);

  annuler2 = gtk_toggle_button_new ();
  gtk_widget_show (annuler2);
  gtk_fixed_put (GTK_FIXED (fixed3), annuler2, 208, 184);
  gtk_widget_set_size_request (annuler2, 109, 29);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (annuler2), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("annuler"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox8), label8, FALSE, FALSE, 0);

  modifier_num = gtk_label_new (_("Saisir le num\303\251ro de la machine"));
  gtk_widget_show (modifier_num);
  gtk_fixed_put (GTK_FIXED (fixed3), modifier_num, 72, 24);
  gtk_widget_set_size_request (modifier_num, 224, 56);

  commentaire = gtk_label_new ("");
  gtk_widget_show (commentaire);
  gtk_fixed_put (GTK_FIXED (fixed3), commentaire, 80, 136);
  gtk_widget_set_size_request (commentaire, 227, 32);

  g_signal_connect ((gpointer) enregistrer2, "clicked",
                    G_CALLBACK (on_enregistrer2_clicked),
                    NULL);
  g_signal_connect ((gpointer) annuler2, "clicked",
                    G_CALLBACK (on_annuler2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Modifier, Modifier, "Modifier");
  GLADE_HOOKUP_OBJECT (Modifier, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (Modifier, modification_num, "modification_num");
  GLADE_HOOKUP_OBJECT (Modifier, enregistrer2, "enregistrer2");
  GLADE_HOOKUP_OBJECT (Modifier, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (Modifier, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (Modifier, image7, "image7");
  GLADE_HOOKUP_OBJECT (Modifier, label7, "label7");
  GLADE_HOOKUP_OBJECT (Modifier, annuler2, "annuler2");
  GLADE_HOOKUP_OBJECT (Modifier, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (Modifier, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (Modifier, image8, "image8");
  GLADE_HOOKUP_OBJECT (Modifier, label8, "label8");
  GLADE_HOOKUP_OBJECT (Modifier, modifier_num, "modifier_num");
  GLADE_HOOKUP_OBJECT (Modifier, commentaire, "commentaire");

  return Modifier;
}

GtkWidget*
create_Supprimer (void)
{
  GtkWidget *Supprimer;
  GtkWidget *fixed4;
  GtkWidget *suppression_num;
  GtkWidget *enregistrer3;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label9;
  GtkWidget *annuler3;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label10;
  GtkWidget *supprimer_num;
  GtkWidget *commentaire1;

  Supprimer = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Supprimer), _("Supprimer"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (Supprimer), fixed4);

  suppression_num = gtk_entry_new ();
  gtk_widget_show (suppression_num);
  gtk_fixed_put (GTK_FIXED (fixed4), suppression_num, 128, 80);
  gtk_widget_set_size_request (suppression_num, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (suppression_num), 8226);

  enregistrer3 = gtk_toggle_button_new ();
  gtk_widget_show (enregistrer3);
  gtk_fixed_put (GTK_FIXED (fixed4), enregistrer3, 88, 160);
  gtk_widget_set_size_request (enregistrer3, 109, 29);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (enregistrer3), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("enregistrer"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox9), label9, FALSE, FALSE, 0);

  annuler3 = gtk_toggle_button_new ();
  gtk_widget_show (annuler3);
  gtk_fixed_put (GTK_FIXED (fixed4), annuler3, 240, 160);
  gtk_widget_set_size_request (annuler3, 117, 29);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (annuler3), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("annuler"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox10), label10, FALSE, FALSE, 0);

  supprimer_num = gtk_label_new (_("Saisir le num\303\251ro de la machine "));
  gtk_widget_show (supprimer_num);
  gtk_fixed_put (GTK_FIXED (fixed4), supprimer_num, 96, 16);
  gtk_widget_set_size_request (supprimer_num, 216, 64);

  commentaire1 = gtk_label_new ("");
  gtk_widget_show (commentaire1);
  gtk_fixed_put (GTK_FIXED (fixed4), commentaire1, 88, 120);
  gtk_widget_set_size_request (commentaire1, 240, 33);

  g_signal_connect ((gpointer) enregistrer3, "clicked",
                    G_CALLBACK (on_enregistrer3_clicked),
                    NULL);
  g_signal_connect ((gpointer) annuler3, "clicked",
                    G_CALLBACK (on_annuler3_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Supprimer, Supprimer, "Supprimer");
  GLADE_HOOKUP_OBJECT (Supprimer, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (Supprimer, suppression_num, "suppression_num");
  GLADE_HOOKUP_OBJECT (Supprimer, enregistrer3, "enregistrer3");
  GLADE_HOOKUP_OBJECT (Supprimer, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (Supprimer, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (Supprimer, image9, "image9");
  GLADE_HOOKUP_OBJECT (Supprimer, label9, "label9");
  GLADE_HOOKUP_OBJECT (Supprimer, annuler3, "annuler3");
  GLADE_HOOKUP_OBJECT (Supprimer, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (Supprimer, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (Supprimer, image10, "image10");
  GLADE_HOOKUP_OBJECT (Supprimer, label10, "label10");
  GLADE_HOOKUP_OBJECT (Supprimer, supprimer_num, "supprimer_num");
  GLADE_HOOKUP_OBJECT (Supprimer, commentaire1, "commentaire1");

  return Supprimer;
}

GtkWidget*
create_Chercher (void)
{
  GtkWidget *Chercher;
  GtkWidget *fixed5;
  GtkWidget *recherche_num;
  GtkWidget *annuler4;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label12;
  GtkWidget *enregistrer4;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label11;
  GtkWidget *chercher_num;
  GtkWidget *commentaire2;

  Chercher = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Chercher), _("Chercher"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (Chercher), fixed5);

  recherche_num = gtk_entry_new ();
  gtk_widget_show (recherche_num);
  gtk_fixed_put (GTK_FIXED (fixed5), recherche_num, 120, 96);
  gtk_widget_set_size_request (recherche_num, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (recherche_num), 8226);

  annuler4 = gtk_toggle_button_new ();
  gtk_widget_show (annuler4);
  gtk_fixed_put (GTK_FIXED (fixed5), annuler4, 248, 168);
  gtk_widget_set_size_request (annuler4, 117, 29);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (annuler4), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("annuler"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox12), label12, FALSE, FALSE, 0);

  enregistrer4 = gtk_toggle_button_new ();
  gtk_widget_show (enregistrer4);
  gtk_fixed_put (GTK_FIXED (fixed5), enregistrer4, 88, 168);
  gtk_widget_set_size_request (enregistrer4, 117, 29);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (enregistrer4), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("enregistrer"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox11), label11, FALSE, FALSE, 0);

  chercher_num = gtk_label_new (_("Saisir le num\303\251ro de la machine "));
  gtk_widget_show (chercher_num);
  gtk_fixed_put (GTK_FIXED (fixed5), chercher_num, 88, 40);
  gtk_widget_set_size_request (chercher_num, 224, 64);

  commentaire2 = gtk_label_new ("");
  gtk_widget_show (commentaire2);
  gtk_fixed_put (GTK_FIXED (fixed5), commentaire2, 80, 128);
  gtk_widget_set_size_request (commentaire2, 240, 32);

  g_signal_connect ((gpointer) annuler4, "clicked",
                    G_CALLBACK (on_annuler4_clicked),
                    NULL);
  g_signal_connect ((gpointer) enregistrer4, "clicked",
                    G_CALLBACK (on_enregistrer4_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Chercher, Chercher, "Chercher");
  GLADE_HOOKUP_OBJECT (Chercher, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (Chercher, recherche_num, "recherche_num");
  GLADE_HOOKUP_OBJECT (Chercher, annuler4, "annuler4");
  GLADE_HOOKUP_OBJECT (Chercher, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (Chercher, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (Chercher, image12, "image12");
  GLADE_HOOKUP_OBJECT (Chercher, label12, "label12");
  GLADE_HOOKUP_OBJECT (Chercher, enregistrer4, "enregistrer4");
  GLADE_HOOKUP_OBJECT (Chercher, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (Chercher, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (Chercher, image11, "image11");
  GLADE_HOOKUP_OBJECT (Chercher, label11, "label11");
  GLADE_HOOKUP_OBJECT (Chercher, chercher_num, "chercher_num");
  GLADE_HOOKUP_OBJECT (Chercher, commentaire2, "commentaire2");

  return Chercher;
}

GtkWidget*
create_Formulaire (void)
{
  GtkWidget *Formulaire;
  GtkWidget *fixed6;
  GtkWidget *entry7_nom;
  GtkWidget *entry8_numero;
  GtkWidget *entry10_cout;
  GtkObject *jour1_adj;
  GtkWidget *jour1;
  GtkObject *mois1_adj;
  GtkWidget *mois1;
  GtkObject *annee1_adj;
  GtkWidget *annee1;
  GtkObject *entry11_duree_adj;
  GtkWidget *entry11_duree;
  GtkWidget *entry11_numero;
  GtkWidget *annuler5;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label14;
  GtkWidget *duree;
  GtkWidget *date_;
  GtkWidget *cout;
  GtkWidget *marque;
  GtkWidget *entry9_marque;
  GtkWidget *nom;
  GtkWidget *enregistrer5;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label13;
  GtkWidget *numero;
  GtkWidget *nouv_num;
  GtkWidget *label19;

  Formulaire = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Formulaire), _("Formulaire"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (Formulaire), fixed6);

  entry7_nom = gtk_entry_new ();
  gtk_widget_show (entry7_nom);
  gtk_fixed_put (GTK_FIXED (fixed6), entry7_nom, 232, 104);
  gtk_widget_set_size_request (entry7_nom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7_nom), 8226);

  entry8_numero = gtk_entry_new ();
  gtk_widget_show (entry8_numero);
  gtk_fixed_put (GTK_FIXED (fixed6), entry8_numero, 232, 64);
  gtk_widget_set_size_request (entry8_numero, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8_numero), 8226);

  entry10_cout = gtk_entry_new ();
  gtk_widget_show (entry10_cout);
  gtk_fixed_put (GTK_FIXED (fixed6), entry10_cout, 232, 184);
  gtk_widget_set_size_request (entry10_cout, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10_cout), 8226);

  jour1_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  jour1 = gtk_spin_button_new (GTK_ADJUSTMENT (jour1_adj), 1, 0);
  gtk_widget_show (jour1);
  gtk_fixed_put (GTK_FIXED (fixed6), jour1, 232, 224);
  gtk_widget_set_size_request (jour1, 60, 27);

  mois1_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  mois1 = gtk_spin_button_new (GTK_ADJUSTMENT (mois1_adj), 1, 0);
  gtk_widget_show (mois1);
  gtk_fixed_put (GTK_FIXED (fixed6), mois1, 296, 224);
  gtk_widget_set_size_request (mois1, 60, 27);

  annee1_adj = gtk_adjustment_new (1990, 1990, 2020, 1, 10, 10);
  annee1 = gtk_spin_button_new (GTK_ADJUSTMENT (annee1_adj), 1, 0);
  gtk_widget_show (annee1);
  gtk_fixed_put (GTK_FIXED (fixed6), annee1, 360, 224);
  gtk_widget_set_size_request (annee1, 60, 27);

  entry11_duree_adj = gtk_adjustment_new (1, 0, 4000, 1, 10, 10);
  entry11_duree = gtk_spin_button_new (GTK_ADJUSTMENT (entry11_duree_adj), 1, 0);
  gtk_widget_show (entry11_duree);
  gtk_fixed_put (GTK_FIXED (fixed6), entry11_duree, 232, 264);
  gtk_widget_set_size_request (entry11_duree, 60, 27);

  entry11_numero = gtk_entry_new ();
  gtk_widget_show (entry11_numero);
  gtk_fixed_put (GTK_FIXED (fixed6), entry11_numero, 232, 24);
  gtk_widget_set_size_request (entry11_numero, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry11_numero), 8226);

  annuler5 = gtk_toggle_button_new ();
  gtk_widget_show (annuler5);
  gtk_fixed_put (GTK_FIXED (fixed6), annuler5, 224, 312);
  gtk_widget_set_size_request (annuler5, 117, 29);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (annuler5), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("annuler"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox14), label14, FALSE, FALSE, 0);

  duree = gtk_label_new (_("La dur\303\251e de fonctionnement "));
  gtk_widget_show (duree);
  gtk_fixed_put (GTK_FIXED (fixed6), duree, 16, 264);
  gtk_widget_set_size_request (duree, 192, 33);

  date_ = gtk_label_new (_("La date d'achat"));
  gtk_widget_show (date_);
  gtk_fixed_put (GTK_FIXED (fixed6), date_, 8, 232);
  gtk_widget_set_size_request (date_, 128, 25);

  cout = gtk_label_new (_("Le cout d'achat"));
  gtk_widget_show (cout);
  gtk_fixed_put (GTK_FIXED (fixed6), cout, 16, 184);
  gtk_widget_set_size_request (cout, 112, 32);

  marque = gtk_label_new (_("La marque"));
  gtk_widget_show (marque);
  gtk_fixed_put (GTK_FIXED (fixed6), marque, 8, 144);
  gtk_widget_set_size_request (marque, 112, 32);

  entry9_marque = gtk_combo_box_new_text ();
  gtk_widget_show (entry9_marque);
  gtk_fixed_put (GTK_FIXED (fixed6), entry9_marque, 232, 144);
  gtk_widget_set_size_request (entry9_marque, 162, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry9_marque), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry9_marque), _("JHON_DEERE"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry9_marque), _("NEW_HOLLAND"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry9_marque), _("FENDT"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry9_marque), _("MASSEY_FERGUSON"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry9_marque), _("CLAAS"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry9_marque), _("CASE_IH"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry9_marque), _("VALTRA"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (entry9_marque), _("KUBOTA"));

  nom = gtk_label_new (_("Nom de l'\303\251quipement "));
  gtk_widget_show (nom);
  gtk_fixed_put (GTK_FIXED (fixed6), nom, 0, 104);
  gtk_widget_set_size_request (nom, 192, 40);

  enregistrer5 = gtk_toggle_button_new ();
  gtk_widget_show (enregistrer5);
  gtk_fixed_put (GTK_FIXED (fixed6), enregistrer5, 56, 312);
  gtk_widget_set_size_request (enregistrer5, 117, 29);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (enregistrer5), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("enregistrer"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox13), label13, FALSE, FALSE, 0);

  numero = gtk_label_new (_("Numero de la machine"));
  gtk_widget_show (numero);
  gtk_fixed_put (GTK_FIXED (fixed6), numero, 16, 16);
  gtk_widget_set_size_request (numero, 176, 40);

  nouv_num = gtk_label_new (_("Nouveau numero de \n          l a machine"));
  gtk_widget_show (nouv_num);
  gtk_fixed_put (GTK_FIXED (fixed6), nouv_num, 16, 64);
  gtk_widget_set_size_request (nouv_num, 160, 32);

  label19 = gtk_label_new (_("jours"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed6), label19, 304, 264);
  gtk_widget_set_size_request (label19, 64, 25);

  g_signal_connect ((gpointer) annuler5, "clicked",
                    G_CALLBACK (on_annuler5_clicked),
                    NULL);
  g_signal_connect ((gpointer) enregistrer5, "clicked",
                    G_CALLBACK (on_enregistrer5_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Formulaire, Formulaire, "Formulaire");
  GLADE_HOOKUP_OBJECT (Formulaire, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (Formulaire, entry7_nom, "entry7_nom");
  GLADE_HOOKUP_OBJECT (Formulaire, entry8_numero, "entry8_numero");
  GLADE_HOOKUP_OBJECT (Formulaire, entry10_cout, "entry10_cout");
  GLADE_HOOKUP_OBJECT (Formulaire, jour1, "jour1");
  GLADE_HOOKUP_OBJECT (Formulaire, mois1, "mois1");
  GLADE_HOOKUP_OBJECT (Formulaire, annee1, "annee1");
  GLADE_HOOKUP_OBJECT (Formulaire, entry11_duree, "entry11_duree");
  GLADE_HOOKUP_OBJECT (Formulaire, entry11_numero, "entry11_numero");
  GLADE_HOOKUP_OBJECT (Formulaire, annuler5, "annuler5");
  GLADE_HOOKUP_OBJECT (Formulaire, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (Formulaire, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (Formulaire, image14, "image14");
  GLADE_HOOKUP_OBJECT (Formulaire, label14, "label14");
  GLADE_HOOKUP_OBJECT (Formulaire, duree, "duree");
  GLADE_HOOKUP_OBJECT (Formulaire, date_, "date_");
  GLADE_HOOKUP_OBJECT (Formulaire, cout, "cout");
  GLADE_HOOKUP_OBJECT (Formulaire, marque, "marque");
  GLADE_HOOKUP_OBJECT (Formulaire, entry9_marque, "entry9_marque");
  GLADE_HOOKUP_OBJECT (Formulaire, nom, "nom");
  GLADE_HOOKUP_OBJECT (Formulaire, enregistrer5, "enregistrer5");
  GLADE_HOOKUP_OBJECT (Formulaire, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (Formulaire, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (Formulaire, image13, "image13");
  GLADE_HOOKUP_OBJECT (Formulaire, label13, "label13");
  GLADE_HOOKUP_OBJECT (Formulaire, numero, "numero");
  GLADE_HOOKUP_OBJECT (Formulaire, nouv_num, "nouv_num");
  GLADE_HOOKUP_OBJECT (Formulaire, label19, "label19");

  return Formulaire;
}

GtkWidget*
create_Afficher (void)
{
  GtkWidget *Afficher;
  GtkWidget *fixed7;
  GtkWidget *treeview1;
  GtkWidget *Liste;
  GtkWidget *Annuler;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label16;

  Afficher = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Afficher), _("Afficher"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (Afficher), fixed7);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed7), treeview1, 8, 64);
  gtk_widget_set_size_request (treeview1, 584, 216);
  gtk_container_set_border_width (GTK_CONTAINER (treeview1), 2);

  Liste = gtk_label_new (_("Liste des \303\251quipements agricoles "));
  gtk_widget_show (Liste);
  gtk_fixed_put (GTK_FIXED (fixed7), Liste, 80, 8);
  gtk_widget_set_size_request (Liste, 264, 33);

  Annuler = gtk_toggle_button_new ();
  gtk_widget_show (Annuler);
  gtk_fixed_put (GTK_FIXED (fixed7), Annuler, 160, 288);
  gtk_widget_set_size_request (Annuler, 109, 29);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (Annuler), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox16), label16, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) Annuler, "clicked",
                    G_CALLBACK (on_Annuler_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Afficher, Afficher, "Afficher");
  GLADE_HOOKUP_OBJECT (Afficher, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (Afficher, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (Afficher, Liste, "Liste");
  GLADE_HOOKUP_OBJECT (Afficher, Annuler, "Annuler");
  GLADE_HOOKUP_OBJECT (Afficher, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (Afficher, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (Afficher, image16, "image16");
  GLADE_HOOKUP_OBJECT (Afficher, label16, "label16");

  return Afficher;
}

GtkWidget*
create_Affichage (void)
{
  GtkWidget *Affichage;
  GtkWidget *fixed8;
  GtkWidget *treeview2;
  GtkWidget *annuler6;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image17;
  GtkWidget *label17;

  Affichage = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Affichage), _("Affichage"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (Affichage), fixed8);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed8), treeview2, 24, 48);
  gtk_widget_set_size_request (treeview2, 520, 72);

  annuler6 = gtk_toggle_button_new ();
  gtk_widget_show (annuler6);
  gtk_fixed_put (GTK_FIXED (fixed8), annuler6, 168, 200);
  gtk_widget_set_size_request (annuler6, 109, 29);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (annuler6), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image17 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox17), image17, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox17), label17, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) annuler6, "clicked",
                    G_CALLBACK (on_annuler6_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Affichage, Affichage, "Affichage");
  GLADE_HOOKUP_OBJECT (Affichage, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (Affichage, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (Affichage, annuler6, "annuler6");
  GLADE_HOOKUP_OBJECT (Affichage, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (Affichage, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (Affichage, image17, "image17");
  GLADE_HOOKUP_OBJECT (Affichage, label17, "label17");

  return Affichage;
}

