/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_gestion_des_troupeaux (void)
{
  GtkWidget *gestion_des_troupeaux;
  GtkWidget *fixed1;
  GtkWidget *treeview1;
  GtkWidget *button1_ajouter;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label6;
  GtkWidget *button2_modifier;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label7;
  GtkWidget *button4_supprimer;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label9;
  GtkWidget *button3_chercher;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label8;
  GtkWidget *afficher_treeview;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label17;
  GtkWidget *calculer1;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image18;
  GtkWidget *label21;

  gestion_des_troupeaux = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (gestion_des_troupeaux), _("Gestion Des Troupeaux"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (gestion_des_troupeaux), fixed1);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed1), treeview1, 200, 16);
  gtk_widget_set_size_request (treeview1, 352, 280);
  gtk_tree_view_set_hover_selection (GTK_TREE_VIEW (treeview1), TRUE);

  button1_ajouter = gtk_button_new ();
  gtk_widget_show (button1_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed1), button1_ajouter, 0, 24);
  gtk_widget_set_size_request (button1_ajouter, 150, 30);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button1_ajouter), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox3), label6, FALSE, FALSE, 0);

  button2_modifier = gtk_button_new ();
  gtk_widget_show (button2_modifier);
  gtk_fixed_put (GTK_FIXED (fixed1), button2_modifier, 0, 72);
  gtk_widget_set_size_request (button2_modifier, 150, 30);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button2_modifier), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox4), label7, FALSE, FALSE, 0);

  button4_supprimer = gtk_button_new ();
  gtk_widget_show (button4_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed1), button4_supprimer, 0, 168);
  gtk_widget_set_size_request (button4_supprimer, 150, 30);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button4_supprimer), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox6), label9, FALSE, FALSE, 0);

  button3_chercher = gtk_button_new ();
  gtk_widget_show (button3_chercher);
  gtk_fixed_put (GTK_FIXED (fixed1), button3_chercher, 0, 120);
  gtk_widget_set_size_request (button3_chercher, 150, 30);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button3_chercher), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox5), label8, FALSE, FALSE, 0);

  afficher_treeview = gtk_button_new ();
  gtk_widget_show (afficher_treeview);
  gtk_fixed_put (GTK_FIXED (fixed1), afficher_treeview, 0, 216);
  gtk_widget_set_size_request (afficher_treeview, 150, 30);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (afficher_treeview), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox14), label17, FALSE, FALSE, 0);

  calculer1 = gtk_button_new ();
  gtk_widget_show (calculer1);
  gtk_fixed_put (GTK_FIXED (fixed1), calculer1, 0, 264);
  gtk_widget_set_size_request (calculer1, 150, 30);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (calculer1), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image18 = gtk_image_new_from_stock ("gtk-dialog-question", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox18), image18, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("Calculer"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox18), label21, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button1_ajouter, "clicked",
                    G_CALLBACK (on_button1_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2_modifier, "clicked",
                    G_CALLBACK (on_button2_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4_supprimer, "clicked",
                    G_CALLBACK (on_button4_supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3_chercher, "clicked",
                    G_CALLBACK (on_button3_chercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) afficher_treeview, "clicked",
                    G_CALLBACK (on_afficher_treeview_clicked),
                    NULL);
  g_signal_connect ((gpointer) calculer1, "clicked",
                    G_CALLBACK (on_calculer1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gestion_des_troupeaux, gestion_des_troupeaux, "gestion_des_troupeaux");
  GLADE_HOOKUP_OBJECT (gestion_des_troupeaux, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (gestion_des_troupeaux, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (gestion_des_troupeaux, button1_ajouter, "button1_ajouter");
  GLADE_HOOKUP_OBJECT (gestion_des_troupeaux, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (gestion_des_troupeaux, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (gestion_des_troupeaux, image3, "image3");
  GLADE_HOOKUP_OBJECT (gestion_des_troupeaux, label6, "label6");
  GLADE_HOOKUP_OBJECT (gestion_des_troupeaux, button2_modifier, "button2_modifier");
  GLADE_HOOKUP_OBJECT (gestion_des_troupeaux, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (gestion_des_troupeaux, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (gestion_des_troupeaux, image4, "image4");
  GLADE_HOOKUP_OBJECT (gestion_des_troupeaux, label7, "label7");
  GLADE_HOOKUP_OBJECT (gestion_des_troupeaux, button4_supprimer, "button4_supprimer");
  GLADE_HOOKUP_OBJECT (gestion_des_troupeaux, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (gestion_des_troupeaux, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (gestion_des_troupeaux, image6, "image6");
  GLADE_HOOKUP_OBJECT (gestion_des_troupeaux, label9, "label9");
  GLADE_HOOKUP_OBJECT (gestion_des_troupeaux, button3_chercher, "button3_chercher");
  GLADE_HOOKUP_OBJECT (gestion_des_troupeaux, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (gestion_des_troupeaux, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (gestion_des_troupeaux, image5, "image5");
  GLADE_HOOKUP_OBJECT (gestion_des_troupeaux, label8, "label8");
  GLADE_HOOKUP_OBJECT (gestion_des_troupeaux, afficher_treeview, "afficher_treeview");
  GLADE_HOOKUP_OBJECT (gestion_des_troupeaux, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (gestion_des_troupeaux, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (gestion_des_troupeaux, image14, "image14");
  GLADE_HOOKUP_OBJECT (gestion_des_troupeaux, label17, "label17");
  GLADE_HOOKUP_OBJECT (gestion_des_troupeaux, calculer1, "calculer1");
  GLADE_HOOKUP_OBJECT (gestion_des_troupeaux, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (gestion_des_troupeaux, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (gestion_des_troupeaux, image18, "image18");
  GLADE_HOOKUP_OBJECT (gestion_des_troupeaux, label21, "label21");

  return gestion_des_troupeaux;
}

GtkWidget*
create_ajouter (void)
{
  GtkWidget *ajouter;
  GtkWidget *fixed2;
  GtkWidget *label5_date_de_naissance;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkWidget *mois;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkWidget *annee;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkWidget *label1_type;
  GtkWidget *label4_sexe;
  GtkWidget *label3;
  GtkWidget *entry2_id;
  GtkWidget *label2_id;
  GtkWidget *button5_ajouter;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label4;
  GtkWidget *button1_annuler_ajout;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label5;
  GtkWidget *combobox1_type;
  GtkWidget *combobox2_sexe;

  ajouter = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajouter), _("Ajouter"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (ajouter), fixed2);

  label5_date_de_naissance = gtk_label_new (_("Date De Naissance : jour"));
  gtk_widget_show (label5_date_de_naissance);
  gtk_fixed_put (GTK_FIXED (fixed2), label5_date_de_naissance, 0, 184);
  gtk_widget_set_size_request (label5_date_de_naissance, 176, 40);

  spinbutton1_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton1, 176, 192);
  gtk_widget_set_size_request (spinbutton1, 60, 27);

  mois = gtk_label_new (_("mois"));
  gtk_widget_show (mois);
  gtk_fixed_put (GTK_FIXED (fixed2), mois, 240, 192);
  gtk_widget_set_size_request (mois, 48, 24);

  spinbutton2_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton2, 288, 192);
  gtk_widget_set_size_request (spinbutton2, 60, 27);

  annee = gtk_label_new (_("ann\303\251e"));
  gtk_widget_show (annee);
  gtk_fixed_put (GTK_FIXED (fixed2), annee, 352, 192);
  gtk_widget_set_size_request (annee, 56, 24);

  spinbutton3_adj = gtk_adjustment_new (2000, 2000, 2020, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton3, 408, 192);
  gtk_widget_set_size_request (spinbutton3, 60, 27);

  label1_type = gtk_label_new (_("Type :"));
  gtk_widget_show (label1_type);
  gtk_fixed_put (GTK_FIXED (fixed2), label1_type, 0, 24);
  gtk_widget_set_size_request (label1_type, 150, 30);

  label4_sexe = gtk_label_new (_("Sexe :"));
  gtk_widget_show (label4_sexe);
  gtk_fixed_put (GTK_FIXED (fixed2), label4_sexe, 0, 135);
  gtk_widget_set_size_request (label4_sexe, 150, 30);

  label3 = gtk_label_new (_("cas de brebi : b***,cas de veau : v***"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed2), label3, 64, 96);
  gtk_widget_set_size_request (label3, 256, 32);

  entry2_id = gtk_entry_new ();
  gtk_widget_show (entry2_id);
  gtk_fixed_put (GTK_FIXED (fixed2), entry2_id, 150, 60);
  gtk_widget_set_size_request (entry2_id, 150, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2_id), 8226);

  label2_id = gtk_label_new (_("Identifiant :"));
  gtk_widget_show (label2_id);
  gtk_fixed_put (GTK_FIXED (fixed2), label2_id, 0, 60);
  gtk_widget_set_size_request (label2_id, 150, 30);

  button5_ajouter = gtk_button_new ();
  gtk_widget_show (button5_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed2), button5_ajouter, 56, 248);
  gtk_widget_set_size_request (button5_ajouter, 150, 30);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button5_ajouter), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox1), label4, FALSE, FALSE, 0);

  button1_annuler_ajout = gtk_button_new ();
  gtk_widget_show (button1_annuler_ajout);
  gtk_fixed_put (GTK_FIXED (fixed2), button1_annuler_ajout, 232, 248);
  gtk_widget_set_size_request (button1_annuler_ajout, 150, 30);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button1_annuler_ajout), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox2), label5, FALSE, FALSE, 0);

  combobox1_type = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1_type);
  gtk_fixed_put (GTK_FIXED (fixed2), combobox1_type, 150, 24);
  gtk_widget_set_size_request (combobox1_type, 150, 30);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1_type), _("Brebi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1_type), _("Veau"));

  combobox2_sexe = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2_sexe);
  gtk_fixed_put (GTK_FIXED (fixed2), combobox2_sexe, 150, 135);
  gtk_widget_set_size_request (combobox2_sexe, 150, 30);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2_sexe), _("Male"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2_sexe), _("Femelle"));

  g_signal_connect ((gpointer) button5_ajouter, "clicked",
                    G_CALLBACK (on_button5_add_clicked),
                    NULL);
  g_signal_connect ((gpointer) button1_annuler_ajout, "clicked",
                    G_CALLBACK (on_button1_annuler_ajout_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajouter, ajouter, "ajouter");
  GLADE_HOOKUP_OBJECT (ajouter, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (ajouter, label5_date_de_naissance, "label5_date_de_naissance");
  GLADE_HOOKUP_OBJECT (ajouter, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (ajouter, mois, "mois");
  GLADE_HOOKUP_OBJECT (ajouter, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (ajouter, annee, "annee");
  GLADE_HOOKUP_OBJECT (ajouter, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (ajouter, label1_type, "label1_type");
  GLADE_HOOKUP_OBJECT (ajouter, label4_sexe, "label4_sexe");
  GLADE_HOOKUP_OBJECT (ajouter, label3, "label3");
  GLADE_HOOKUP_OBJECT (ajouter, entry2_id, "entry2_id");
  GLADE_HOOKUP_OBJECT (ajouter, label2_id, "label2_id");
  GLADE_HOOKUP_OBJECT (ajouter, button5_ajouter, "button5_ajouter");
  GLADE_HOOKUP_OBJECT (ajouter, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (ajouter, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (ajouter, image1, "image1");
  GLADE_HOOKUP_OBJECT (ajouter, label4, "label4");
  GLADE_HOOKUP_OBJECT (ajouter, button1_annuler_ajout, "button1_annuler_ajout");
  GLADE_HOOKUP_OBJECT (ajouter, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (ajouter, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (ajouter, image2, "image2");
  GLADE_HOOKUP_OBJECT (ajouter, label5, "label5");
  GLADE_HOOKUP_OBJECT (ajouter, combobox1_type, "combobox1_type");
  GLADE_HOOKUP_OBJECT (ajouter, combobox2_sexe, "combobox2_sexe");

  return ajouter;
}

GtkWidget*
create_modifier (void)
{
  GtkWidget *modifier;
  GtkWidget *fixed3;
  GtkWidget *label4_modifier;
  GtkWidget *entry1_modifier;
  GtkWidget *button10_annuler;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label11;
  GtkWidget *button1_modifier;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label10;
  GtkWidget *commentaire;

  modifier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifier), _("Modifier"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (modifier), fixed3);

  label4_modifier = gtk_label_new (_("Donner l'indentifiant :"));
  gtk_widget_show (label4_modifier);
  gtk_fixed_put (GTK_FIXED (fixed3), label4_modifier, 16, 56);
  gtk_widget_set_size_request (label4_modifier, 160, 32);

  entry1_modifier = gtk_entry_new ();
  gtk_widget_show (entry1_modifier);
  gtk_fixed_put (GTK_FIXED (fixed3), entry1_modifier, 176, 56);
  gtk_widget_set_size_request (entry1_modifier, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1_modifier), 8226);

  button10_annuler = gtk_button_new ();
  gtk_widget_show (button10_annuler);
  gtk_fixed_put (GTK_FIXED (fixed3), button10_annuler, 208, 120);
  gtk_widget_set_size_request (button10_annuler, 150, 30);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button10_annuler), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox8), label11, FALSE, FALSE, 0);

  button1_modifier = gtk_button_new ();
  gtk_widget_show (button1_modifier);
  gtk_fixed_put (GTK_FIXED (fixed3), button1_modifier, 40, 120);
  gtk_widget_set_size_request (button1_modifier, 150, 30);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button1_modifier), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox7), label10, FALSE, FALSE, 0);

  commentaire = gtk_label_new ("");
  gtk_widget_show (commentaire);
  gtk_fixed_put (GTK_FIXED (fixed3), commentaire, 48, 184);
  gtk_widget_set_size_request (commentaire, 300, 60);

  g_signal_connect ((gpointer) button10_annuler, "clicked",
                    G_CALLBACK (on_button10_annuler_clicked),
                    NULL);
  g_signal_connect ((gpointer) button1_modifier, "clicked",
                    G_CALLBACK (on_button1_modifier_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifier, modifier, "modifier");
  GLADE_HOOKUP_OBJECT (modifier, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (modifier, label4_modifier, "label4_modifier");
  GLADE_HOOKUP_OBJECT (modifier, entry1_modifier, "entry1_modifier");
  GLADE_HOOKUP_OBJECT (modifier, button10_annuler, "button10_annuler");
  GLADE_HOOKUP_OBJECT (modifier, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (modifier, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (modifier, image8, "image8");
  GLADE_HOOKUP_OBJECT (modifier, label11, "label11");
  GLADE_HOOKUP_OBJECT (modifier, button1_modifier, "button1_modifier");
  GLADE_HOOKUP_OBJECT (modifier, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (modifier, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (modifier, image7, "image7");
  GLADE_HOOKUP_OBJECT (modifier, label10, "label10");
  GLADE_HOOKUP_OBJECT (modifier, commentaire, "commentaire");

  return modifier;
}

GtkWidget*
create_chercher (void)
{
  GtkWidget *chercher;
  GtkWidget *fixed4;
  GtkWidget *label6_chercher;
  GtkWidget *entry4_chercher;
  GtkWidget *button6_cherche;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label12;
  GtkWidget *button_annuler_chercher;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label13;
  GtkWidget *commantaire2;

  chercher = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (chercher), _("Chercher"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (chercher), fixed4);

  label6_chercher = gtk_label_new (_("Donner l'identifiant :"));
  gtk_widget_show (label6_chercher);
  gtk_fixed_put (GTK_FIXED (fixed4), label6_chercher, 16, 72);
  gtk_widget_set_size_request (label6_chercher, 160, 48);

  entry4_chercher = gtk_entry_new ();
  gtk_widget_show (entry4_chercher);
  gtk_fixed_put (GTK_FIXED (fixed4), entry4_chercher, 168, 80);
  gtk_widget_set_size_request (entry4_chercher, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4_chercher), 8226);

  button6_cherche = gtk_button_new ();
  gtk_widget_show (button6_cherche);
  gtk_fixed_put (GTK_FIXED (fixed4), button6_cherche, 24, 152);
  gtk_widget_set_size_request (button6_cherche, 150, 30);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button6_cherche), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("chercher"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox9), label12, FALSE, FALSE, 0);

  button_annuler_chercher = gtk_button_new ();
  gtk_widget_show (button_annuler_chercher);
  gtk_fixed_put (GTK_FIXED (fixed4), button_annuler_chercher, 184, 152);
  gtk_widget_set_size_request (button_annuler_chercher, 150, 30);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button_annuler_chercher), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox10), label13, FALSE, FALSE, 0);

  commantaire2 = gtk_label_new ("");
  gtk_widget_show (commantaire2);
  gtk_fixed_put (GTK_FIXED (fixed4), commantaire2, 24, 208);
  gtk_widget_set_size_request (commantaire2, 310, 60);

  g_signal_connect ((gpointer) button6_cherche, "clicked",
                    G_CALLBACK (on_button6_cherche_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_annuler_chercher, "clicked",
                    G_CALLBACK (on_button_annuler_chercher_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (chercher, chercher, "chercher");
  GLADE_HOOKUP_OBJECT (chercher, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (chercher, label6_chercher, "label6_chercher");
  GLADE_HOOKUP_OBJECT (chercher, entry4_chercher, "entry4_chercher");
  GLADE_HOOKUP_OBJECT (chercher, button6_cherche, "button6_cherche");
  GLADE_HOOKUP_OBJECT (chercher, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (chercher, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (chercher, image9, "image9");
  GLADE_HOOKUP_OBJECT (chercher, label12, "label12");
  GLADE_HOOKUP_OBJECT (chercher, button_annuler_chercher, "button_annuler_chercher");
  GLADE_HOOKUP_OBJECT (chercher, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (chercher, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (chercher, image10, "image10");
  GLADE_HOOKUP_OBJECT (chercher, label13, "label13");
  GLADE_HOOKUP_OBJECT (chercher, commantaire2, "commantaire2");

  return chercher;
}

GtkWidget*
create_supprimer (void)
{
  GtkWidget *supprimer;
  GtkWidget *fixed5;
  GtkWidget *label7_supprimer;
  GtkWidget *entry5_supprimer;
  GtkWidget *button8_supprimer;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label15;
  GtkWidget *button_annuler_supprimer;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label14;
  GtkWidget *commentaire1;

  supprimer = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (supprimer), _("Supprimer"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (supprimer), fixed5);

  label7_supprimer = gtk_label_new (_("donner l'identifiant :"));
  gtk_widget_show (label7_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed5), label7_supprimer, 24, 32);
  gtk_widget_set_size_request (label7_supprimer, 144, 48);

  entry5_supprimer = gtk_entry_new ();
  gtk_widget_show (entry5_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed5), entry5_supprimer, 168, 40);
  gtk_widget_set_size_request (entry5_supprimer, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5_supprimer), 8226);

  button8_supprimer = gtk_button_new ();
  gtk_widget_show (button8_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed5), button8_supprimer, 40, 112);
  gtk_widget_set_size_request (button8_supprimer, 150, 30);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button8_supprimer), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox12), label15, FALSE, FALSE, 0);

  button_annuler_supprimer = gtk_button_new ();
  gtk_widget_show (button_annuler_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed5), button_annuler_supprimer, 200, 112);
  gtk_widget_set_size_request (button_annuler_supprimer, 150, 30);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button_annuler_supprimer), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("Annulier"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox11), label14, FALSE, FALSE, 0);

  commentaire1 = gtk_label_new ("");
  gtk_widget_show (commentaire1);
  gtk_fixed_put (GTK_FIXED (fixed5), commentaire1, 48, 168);
  gtk_widget_set_size_request (commentaire1, 300, 50);

  g_signal_connect ((gpointer) button8_supprimer, "clicked",
                    G_CALLBACK (on_button8_supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_annuler_supprimer, "clicked",
                    G_CALLBACK (on_button_annuler_supprimer_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (supprimer, supprimer, "supprimer");
  GLADE_HOOKUP_OBJECT (supprimer, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (supprimer, label7_supprimer, "label7_supprimer");
  GLADE_HOOKUP_OBJECT (supprimer, entry5_supprimer, "entry5_supprimer");
  GLADE_HOOKUP_OBJECT (supprimer, button8_supprimer, "button8_supprimer");
  GLADE_HOOKUP_OBJECT (supprimer, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (supprimer, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (supprimer, image12, "image12");
  GLADE_HOOKUP_OBJECT (supprimer, label15, "label15");
  GLADE_HOOKUP_OBJECT (supprimer, button_annuler_supprimer, "button_annuler_supprimer");
  GLADE_HOOKUP_OBJECT (supprimer, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (supprimer, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (supprimer, image11, "image11");
  GLADE_HOOKUP_OBJECT (supprimer, label14, "label14");
  GLADE_HOOKUP_OBJECT (supprimer, commentaire1, "commentaire1");

  return supprimer;
}

GtkWidget*
create_formulaire (void)
{
  GtkWidget *formulaire;
  GtkWidget *fixed6;
  GtkWidget *type;
  GtkWidget *entry_id_mod;
  GtkObject *spinbutton_jour_mod_adj;
  GtkWidget *spinbutton_jour_mod;
  GtkObject *spinbutton_mois_mod_adj;
  GtkWidget *spinbutton_mois_mod;
  GtkObject *spinbutton6_adj;
  GtkWidget *spinbutton6;
  GtkWidget *combobox_type_mod;
  GtkWidget *confirmer_mod;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label18;
  GtkWidget *annuler_mod;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label19;
  GtkWidget *date_mod;
  GtkWidget *mois_mod;
  GtkWidget *annee_mod;
  GtkWidget *sexe_mod;
  GtkWidget *combobox_sexe_mod;
  GtkWidget *remarque_;
  GtkWidget *entry_old_id;
  GtkWidget *identifiant_mod;
  GtkWidget *label_old_id;

  formulaire = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (formulaire), _("Modification"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (formulaire), fixed6);

  type = gtk_label_new (_("Type :"));
  gtk_widget_show (type);
  gtk_fixed_put (GTK_FIXED (fixed6), type, 0, 32);
  gtk_widget_set_size_request (type, 150, 30);

  entry_id_mod = gtk_entry_new ();
  gtk_widget_show (entry_id_mod);
  gtk_fixed_put (GTK_FIXED (fixed6), entry_id_mod, 144, 135);
  gtk_widget_set_size_request (entry_id_mod, 150, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id_mod), 8226);

  spinbutton_jour_mod_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton_jour_mod = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_jour_mod_adj), 1, 0);
  gtk_widget_show (spinbutton_jour_mod);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton_jour_mod, 184, 248);
  gtk_widget_set_size_request (spinbutton_jour_mod, 60, 30);

  spinbutton_mois_mod_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton_mois_mod = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_mois_mod_adj), 1, 0);
  gtk_widget_show (spinbutton_mois_mod);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton_mois_mod, 296, 248);
  gtk_widget_set_size_request (spinbutton_mois_mod, 60, 30);

  spinbutton6_adj = gtk_adjustment_new (2000, 2000, 2020, 1, 10, 10);
  spinbutton6 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6_adj), 1, 0);
  gtk_widget_show (spinbutton6);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton6, 408, 248);
  gtk_widget_set_size_request (spinbutton6, 60, 30);

  combobox_type_mod = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_type_mod);
  gtk_fixed_put (GTK_FIXED (fixed6), combobox_type_mod, 144, 32);
  gtk_widget_set_size_request (combobox_type_mod, 150, 30);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_type_mod), _("Brebi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_type_mod), _("Veau"));

  confirmer_mod = gtk_button_new ();
  gtk_widget_show (confirmer_mod);
  gtk_fixed_put (GTK_FIXED (fixed6), confirmer_mod, 88, 296);
  gtk_widget_set_size_request (confirmer_mod, 150, 30);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (confirmer_mod), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox15), label18, FALSE, FALSE, 0);

  annuler_mod = gtk_button_new ();
  gtk_widget_show (annuler_mod);
  gtk_fixed_put (GTK_FIXED (fixed6), annuler_mod, 248, 296);
  gtk_widget_set_size_request (annuler_mod, 150, 30);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (annuler_mod), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox16), label19, FALSE, FALSE, 0);

  date_mod = gtk_label_new (_("Date De Naissance : jour"));
  gtk_widget_show (date_mod);
  gtk_fixed_put (GTK_FIXED (fixed6), date_mod, 0, 248);
  gtk_widget_set_size_request (date_mod, 192, 30);

  mois_mod = gtk_label_new (_("mois"));
  gtk_widget_show (mois_mod);
  gtk_fixed_put (GTK_FIXED (fixed6), mois_mod, 248, 248);
  gtk_widget_set_size_request (mois_mod, 49, 30);

  annee_mod = gtk_label_new (_("ann\303\251e"));
  gtk_widget_show (annee_mod);
  gtk_fixed_put (GTK_FIXED (fixed6), annee_mod, 360, 248);
  gtk_widget_set_size_request (annee_mod, 49, 30);

  sexe_mod = gtk_label_new (_("Sexe :"));
  gtk_widget_show (sexe_mod);
  gtk_fixed_put (GTK_FIXED (fixed6), sexe_mod, 0, 200);
  gtk_widget_set_size_request (sexe_mod, 150, 30);

  combobox_sexe_mod = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_sexe_mod);
  gtk_fixed_put (GTK_FIXED (fixed6), combobox_sexe_mod, 144, 200);
  gtk_widget_set_size_request (combobox_sexe_mod, 150, 30);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_sexe_mod), _("Male"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_sexe_mod), _("Femelle"));

  remarque_ = gtk_label_new (_("cas de brebi : b** , cas de veau : v***"));
  gtk_widget_show (remarque_);
  gtk_fixed_put (GTK_FIXED (fixed6), remarque_, 48, 170);
  gtk_widget_set_size_request (remarque_, 300, 30);

  entry_old_id = gtk_entry_new ();
  gtk_widget_show (entry_old_id);
  gtk_fixed_put (GTK_FIXED (fixed6), entry_old_id, 144, 88);
  gtk_widget_set_size_request (entry_old_id, 150, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_old_id), 8226);

  identifiant_mod = gtk_label_new (_("Nouveau identifiant :"));
  gtk_widget_show (identifiant_mod);
  gtk_fixed_put (GTK_FIXED (fixed6), identifiant_mod, 0, 135);
  gtk_widget_set_size_request (identifiant_mod, 150, 30);

  label_old_id = gtk_label_new (_("ancien identifiant :"));
  gtk_widget_show (label_old_id);
  gtk_fixed_put (GTK_FIXED (fixed6), label_old_id, 0, 88);
  gtk_widget_set_size_request (label_old_id, 150, 30);

  g_signal_connect ((gpointer) confirmer_mod, "clicked",
                    G_CALLBACK (on_confirmer_mod_clicked),
                    NULL);
  g_signal_connect ((gpointer) annuler_mod, "clicked",
                    G_CALLBACK (on_annuler_mod_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (formulaire, formulaire, "formulaire");
  GLADE_HOOKUP_OBJECT (formulaire, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (formulaire, type, "type");
  GLADE_HOOKUP_OBJECT (formulaire, entry_id_mod, "entry_id_mod");
  GLADE_HOOKUP_OBJECT (formulaire, spinbutton_jour_mod, "spinbutton_jour_mod");
  GLADE_HOOKUP_OBJECT (formulaire, spinbutton_mois_mod, "spinbutton_mois_mod");
  GLADE_HOOKUP_OBJECT (formulaire, spinbutton6, "spinbutton6");
  GLADE_HOOKUP_OBJECT (formulaire, combobox_type_mod, "combobox_type_mod");
  GLADE_HOOKUP_OBJECT (formulaire, confirmer_mod, "confirmer_mod");
  GLADE_HOOKUP_OBJECT (formulaire, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (formulaire, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (formulaire, image15, "image15");
  GLADE_HOOKUP_OBJECT (formulaire, label18, "label18");
  GLADE_HOOKUP_OBJECT (formulaire, annuler_mod, "annuler_mod");
  GLADE_HOOKUP_OBJECT (formulaire, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (formulaire, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (formulaire, image16, "image16");
  GLADE_HOOKUP_OBJECT (formulaire, label19, "label19");
  GLADE_HOOKUP_OBJECT (formulaire, date_mod, "date_mod");
  GLADE_HOOKUP_OBJECT (formulaire, mois_mod, "mois_mod");
  GLADE_HOOKUP_OBJECT (formulaire, annee_mod, "annee_mod");
  GLADE_HOOKUP_OBJECT (formulaire, sexe_mod, "sexe_mod");
  GLADE_HOOKUP_OBJECT (formulaire, combobox_sexe_mod, "combobox_sexe_mod");
  GLADE_HOOKUP_OBJECT (formulaire, remarque_, "remarque_");
  GLADE_HOOKUP_OBJECT (formulaire, entry_old_id, "entry_old_id");
  GLADE_HOOKUP_OBJECT (formulaire, identifiant_mod, "identifiant_mod");
  GLADE_HOOKUP_OBJECT (formulaire, label_old_id, "label_old_id");

  return formulaire;
}

GtkWidget*
create_chercher_aff (void)
{
  GtkWidget *chercher_aff;
  GtkWidget *fixed7;
  GtkWidget *treeview2;
  GtkWidget *return_chercher;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image17;
  GtkWidget *label20;

  chercher_aff = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (chercher_aff), _("Chercher"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (chercher_aff), fixed7);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed7), treeview2, 16, 16);
  gtk_widget_set_size_request (treeview2, 416, 72);

  return_chercher = gtk_button_new ();
  gtk_widget_show (return_chercher);
  gtk_fixed_put (GTK_FIXED (fixed7), return_chercher, 136, 128);
  gtk_widget_set_size_request (return_chercher, 150, 30);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (return_chercher), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image17 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox17), image17, FALSE, FALSE, 0);

  label20 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox17), label20, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview2, "row_activated",
                    G_CALLBACK (on_treeview2_row_activated),
                    NULL);
  g_signal_connect ((gpointer) return_chercher, "clicked",
                    G_CALLBACK (on_return_chercher_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (chercher_aff, chercher_aff, "chercher_aff");
  GLADE_HOOKUP_OBJECT (chercher_aff, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (chercher_aff, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (chercher_aff, return_chercher, "return_chercher");
  GLADE_HOOKUP_OBJECT (chercher_aff, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (chercher_aff, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (chercher_aff, image17, "image17");
  GLADE_HOOKUP_OBJECT (chercher_aff, label20, "label20");

  return chercher_aff;
}

GtkWidget*
create_calcul (void)
{
  GtkWidget *calcul;
  GtkWidget *fixed8;
  GtkWidget *resultat;
  GtkWidget *annuler_calcul;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image19;
  GtkWidget *label22;
  GtkWidget *button_calculer;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image20;
  GtkWidget *label23;

  calcul = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (calcul), _("Calcul"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (calcul), fixed8);

  resultat = gtk_label_new ("");
  gtk_widget_show (resultat);
  gtk_fixed_put (GTK_FIXED (fixed8), resultat, 64, 32);
  gtk_widget_set_size_request (resultat, 400, 80);

  annuler_calcul = gtk_button_new ();
  gtk_widget_show (annuler_calcul);
  gtk_fixed_put (GTK_FIXED (fixed8), annuler_calcul, 288, 144);
  gtk_widget_set_size_request (annuler_calcul, 150, 30);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (annuler_calcul), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image19 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox19), image19, FALSE, FALSE, 0);

  label22 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox19), label22, FALSE, FALSE, 0);

  button_calculer = gtk_button_new ();
  gtk_widget_show (button_calculer);
  gtk_fixed_put (GTK_FIXED (fixed8), button_calculer, 104, 144);
  gtk_widget_set_size_request (button_calculer, 150, 30);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (button_calculer), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image20 = gtk_image_new_from_stock ("gtk-help", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox20), image20, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("Calculer"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox20), label23, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) annuler_calcul, "clicked",
                    G_CALLBACK (on_annuler_calcul_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_calculer, "clicked",
                    G_CALLBACK (on_button_calculer_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (calcul, calcul, "calcul");
  GLADE_HOOKUP_OBJECT (calcul, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (calcul, resultat, "resultat");
  GLADE_HOOKUP_OBJECT (calcul, annuler_calcul, "annuler_calcul");
  GLADE_HOOKUP_OBJECT (calcul, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (calcul, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (calcul, image19, "image19");
  GLADE_HOOKUP_OBJECT (calcul, label22, "label22");
  GLADE_HOOKUP_OBJECT (calcul, button_calculer, "button_calculer");
  GLADE_HOOKUP_OBJECT (calcul, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (calcul, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (calcul, image20, "image20");
  GLADE_HOOKUP_OBJECT (calcul, label23, "label23");

  return calcul;
}

