/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_gestion_des_troupeaux (void);
GtkWidget* create_ajouter (void);
GtkWidget* create_modifier (void);
GtkWidget* create_chercher (void);
GtkWidget* create_supprimer (void);
GtkWidget* create_formulaire (void);
GtkWidget* create_chercher_aff (void);
GtkWidget* create_calcul (void);
